load("@rules_python//python:py_test.bzl", "py_test")

py_test(
    name = "test_r11_refusal",
    srcs = [
        "__init__.py",
        "pty_harness.py",
        "test_r11_refusal.py",
        "//:pytest_main.py",
        "//tests:__init__.py",
    ],
    args = ["$(location :test_r11_refusal.py)"],
    data = ["//src/blare:blare"],
    legacy_create_init = False,
    main = "//:pytest_main.py",
    tags = ["e2e"],
    deps = [
        "@pip//pytest_bazel",
        "@rules_python//python/runfiles",
    ],
)

py_test(
    name = "test_seam_through",
    srcs = [
        "__init__.py",
        "pty_harness.py",
        "test_seam_through.py",
        "//:pytest_main.py",
        "//tests:__init__.py",
    ],
    args = ["$(location :test_seam_through.py)"],
    data = [
        "//src/blare:blare",
        "//tests/fixtures/claude-sdk/handshake:handshake.jsonl",
    ],
    legacy_create_init = False,
    main = "//:pytest_main.py",
    tags = ["e2e"],
    deps = [
        "@pip//pytest_bazel",
        "@rules_python//python/runfiles",
    ],
)
