"""Everything under `.blare/` (architecture: no other module touches it): schemas,
structural load-time validation (R19), the semantic-invariant check (R4-R5 plus the
excluded-empty-sets property), state and config (R23, R24), gap counting.

This module (T1.4) implements the read side only: `state_exists`, `init_inspection`,
`empty_set`, `load`, `semantic_violations`, `gap_counts`. The write side --
`batch_check`, `apply`, `referencing_phases`, `render_docs`, `raw_bytes_match`, and the
three write primitives -- is T1.5, per `engineering/modules/artifacts.md`.

Throughout this module, `root` names the `.blare/` directory itself (the layout tree in
`engineering/architecture.md`'s "Artifact file layout" section is rooted there) -- not
the target repo's root. The orchestrator is expected to pass `repo_root / ".blare"`.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import cast

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedSeq

from blare.model import BlareError, RunMode, Violation, ViolationKind
from blare.stack import ObservabilityStack, get_stack, supported_stacks

CURRENT_SCHEMA_VERSION = 1

# The first line every derived doc (docs/*.md) must carry (spec, Artifacts: "generated --
# do not edit"). Exact wording is this module's own choice -- nothing upstream fixes it --
# but it must stay stable: `load` checks it on every read, and T1.5's rendering (out of
# this task's scope) must produce it verbatim.
GENERATED_DOC_HEADER = (
    "<!-- Generated by blare. Do not edit -- changes are overwritten on the next run. -->"
)

_STATE_FILENAME = "state.yaml"
_CONFIG_FILENAME = "config.yaml"
_DOCS_DIRNAME = "docs"
_DEFAULT_STACK_NAME = "prometheus"

# Canonical entry-based files, keyed by the ArtifactSet field they populate, in the
# architecture's layout order. Every value here is also a "path derived docs use" once
# its basename is run through `_doc_path`.
_ENTRY_FILENAMES: dict[str, str] = {
    "system_components": "system-map.yaml",
    "failure_modes": "failure-modes.yaml",
    "metrics": "metrics.yaml",
    "metric_recommendations": "metric-recommendations.yaml",
    "alert_recommendations": "alert-recommendations.yaml",
    "coverage": "coverage.yaml",
}

_COMPONENT_KINDS = (
    "service",
    "worker",
    "job",
    "external-dependency",
    "datastore",
    "entrypoint",
)
_SEVERITIES = ("critical", "warning")
_COVERAGE_STATUSES = ("alertable", "metric-gap", "excluded")
_METRIC_TYPES = ("counter", "gauge", "histogram", "summary")
_RECOMMENDATION_KINDS = ("new", "change")

_SEVERITY_RANK: dict[str, int] = {"warning": 0, "critical": 1}

# One shared round-trip YAML (de)serializer. Round-trip mode (not safe/rt-lite) is what
# lets T1.5 preserve hand-formatting on entries an edit batch never touches (R9/R16); this
# task only reads, but loads through the same instance so the parsed representation is
# exactly what T1.5 builds its surgical writes on.
_YAML = YAML(typ="rt")
_YAML.preserve_quotes = True


class StructuralValidationError(BlareError):
    """One of R19's structural rules failed on load: schema conformance, a dangling
    reference, a `caused_by` cycle, a missing required field, a missing exclusion reason,
    a missing or duplicate coverage entry, an unparseable or incomplete state file, an
    unreadable or missing entry file, or a headerless file at a derived-doc path. Cause
    names the file and the exact problem, verbatim (R13)."""


class StateMissingError(BlareError):
    """`load` (or `state_exists`'s caller) found no `state.yaml` (R17's identity): `blare
    update` needs a prior `blare analyze`. Message names `blare analyze` as the fix."""


class PreexistingFilesError(BlareError):
    """`init_inspection` found canonical entry-based files or derived-doc-path files with
    no state file present (R1's inverse refusal). An existing `config.yaml` alone never
    triggers this. Cause names every offending file."""


class ConfigError(BlareError):
    """`config.yaml` is missing (update mode only, R23), unparseable, or parses without a
    usable `stack` value (empty/null document included). Names the file and the supported
    stack values. An *unsupported* stack name is not this error: it propagates stack's own
    `UnsupportedStackError` unchanged, which already names the file's fixed path (it is
    never configurable, spec's Artifacts section) and the supported values."""


class SchemaVersionError(BlareError):
    """`state.yaml`'s `schema_version` does not match `CURRENT_SCHEMA_VERSION` (R24).
    Cause names both versions; distinct from `StructuralValidationError` since the
    recovery (run the matching Blare version, or discard and re-analyze) differs from a
    plain data-shape fix."""


# --- Entry types -------------------------------------------------------------------


@dataclass(frozen=True)
class SystemComponent:
    """One system-map entry (`system-map.yaml`, phase 1). `kind` is one of
    `_COMPONENT_KINDS`; `depends_on` names other `sm-` ids."""

    id: str
    name: str
    kind: str
    description: str
    depends_on: tuple[str, ...]


@dataclass(frozen=True)
class FailureMode:
    """One failure-mode entry (`failure-modes.yaml`, phase 2). `severity` is one of
    `_SEVERITIES`; `coverage_status` is one of `_COVERAGE_STATUSES`; `caused_by` names
    other `fm-` ids (the causal graph, R3); `exclusion_reason` is required iff
    `coverage_status == "excluded"`."""

    id: str
    title: str
    description: str
    severity: str
    user_visible: bool
    caused_by: tuple[str, ...]
    coverage_status: str
    exclusion_reason: str | None


@dataclass(frozen=True)
class Metric:
    """One implemented-metric entry (`metrics.yaml`, phase 3). `type` is one of
    `_METRIC_TYPES`; `emitted_at` is a list of `path:line` locations."""

    id: str
    name: str
    type: str
    labels: tuple[str, ...]
    emitted_at: tuple[str, ...]
    description: str


@dataclass(frozen=True)
class MetricRecommendation:
    """One metric-change recommendation (`metric-recommendations.yaml`, phase 3). `kind`
    is `new` or `change`; `metric_id` (an `mx-` id) is required iff `kind == "change"` and
    forbidden otherwise. `failure_mode_ids` non-emptiness is a semantic invariant (R5), not
    schema."""

    id: str
    kind: str
    metric_id: str | None
    failure_mode_ids: tuple[str, ...]
    rationale: str
    details: str


@dataclass(frozen=True)
class AlertRecommendation:
    """One alert recommendation (`alert-recommendations.yaml`, phase 4). `severity` is one
    of `_SEVERITIES`; `annotations` must carry `summary` and `description` keys (schema);
    `failure_mode_ids` non-emptiness and `expr` validity are semantic invariants (R4-R5),
    not schema."""

    id: str
    name: str
    expr: str
    for_duration: str
    severity: str
    failure_mode_ids: tuple[str, ...]
    annotations: Mapping[str, str]


@dataclass(frozen=True)
class CoverageEntry:
    """One coverage-mapping entry (`coverage.yaml`, spanning phases 3-4). Keyed by
    `failure_mode_id` -- the one exception to the `<prefix>-<slug>` id scheme (artifacts.md)
    -- with exactly one entry per failure mode, excluded ones included."""

    failure_mode_id: str
    detecting_metric_ids: tuple[str, ...]
    metric_recommendation_ids: tuple[str, ...]
    alert_ids: tuple[str, ...]


@dataclass(frozen=True)
class GapSummary:
    """Non-excluded failure modes split by coverage status (R13's gap count); `excluded`
    is carried for context only -- an excluded failure mode is never a gap (Terms)."""

    alertable: int
    metric_gap: int
    excluded: int


@dataclass
class ArtifactSet:
    """The in-memory whole artifact set (architecture: `artifacts` owns everything under
    `.blare/`): typed entry maps, the state fields, the resolved stack handle, and the
    loaded representation T1.5 builds surgical writes on.

    `raw_bytes` is keyed by canonical filename and covers the entry files plus
    `state.yaml` (the R20 comparison baseline, `raw_bytes_match`) -- `config.yaml` is
    excluded, matching R20's own carve-out (artifacts.md: "config.yaml is outside the
    comparison"). `documents` is keyed by entry-file filename only (state.yaml is a
    mapping of two scalar fields, always rewritten wholesale by `write_state` rather than
    surgically merged, so there is no round-trip document worth retaining for it): each
    entry file's round-trip-parsed `CommentedSeq`, the list T1.5's surgical edit
    application locates entries in without disturbing untouched ones' formatting. Both
    are empty on the fresh `empty_set` baseline, matching `init_inspection` having
    verified nothing was at those paths.

    A later `apply` (T1.5) must return a new `ArtifactSet` rather than mutate this one in
    place -- the entry maps and `raw_bytes`/`documents` dicts here are plain, mutable
    containers only because dataclasses do not enforce immutability of their contents;
    `apply`'s purity is a caller discipline this module does not currently enforce
    structurally.
    """

    system_components: dict[str, SystemComponent]
    failure_modes: dict[str, FailureMode]
    metrics: dict[str, Metric]
    metric_recommendations: dict[str, MetricRecommendation]
    alert_recommendations: dict[str, AlertRecommendation]
    coverage: dict[str, CoverageEntry]
    analyzed_sha: str | None
    schema_version: int
    stack_name: str
    stack: ObservabilityStack
    config_existed: bool
    raw_bytes: dict[str, bytes]
    documents: dict[str, CommentedSeq]


# --- Small parsing helpers -----------------------------------------------------------


def _err(file: Path, problem: str) -> StructuralValidationError:
    return StructuralValidationError(
        cause=f"{file}: {problem}",
        next_action=(
            "Fix the file by hand (see the problem above), or restore .blare/ from git, "
            "then re-run blare."
        ),
    )


def _doc_path(root: Path, entry_filename: str) -> Path:
    return root / _DOCS_DIRNAME / f"{Path(entry_filename).stem}.md"


def _read_bytes(path: Path) -> bytes:
    try:
        return path.read_bytes()
    except OSError as exc:
        raise _err(path, f"could not be read ({exc.strerror or exc})") from exc


def _str_field(file: Path, item: Mapping[str, object], key: str, desc: str) -> str:
    value = item.get(key)
    if not isinstance(value, str) or not value:
        raise _err(file, f"{desc} is missing a non-empty string {key!r}")
    return value


def _optional_str_field(
    file: Path, item: Mapping[str, object], key: str, desc: str
) -> str | None:
    if key not in item or item[key] is None:
        return None
    value = item[key]
    if not isinstance(value, str):
        raise _err(file, f"{desc}'s {key!r} must be a string")
    return value


def _bool_field(file: Path, item: Mapping[str, object], key: str, desc: str) -> bool:
    value = item.get(key)
    if not isinstance(value, bool):
        raise _err(file, f"{desc} is missing a boolean {key!r}")
    return value


def _enum_field(
    file: Path, item: Mapping[str, object], key: str, desc: str, allowed: Sequence[str]
) -> str:
    value = item.get(key)
    if value not in allowed:
        raise _err(file, f"{desc}'s {key!r} must be one of {list(allowed)}, got {value!r}")
    assert isinstance(value, str)  # narrowed by the membership check above
    return value


def _str_list_field(
    file: Path, item: Mapping[str, object], key: str, desc: str
) -> tuple[str, ...]:
    value = item.get(key, [])
    if value is None:
        value = []
    if not isinstance(value, list) or not all(isinstance(v, str) for v in value):
        raise _err(file, f"{desc}'s {key!r} must be a list of strings")
    return tuple(value)


def _str_map_field(
    file: Path,
    item: Mapping[str, object],
    key: str,
    desc: str,
    required_keys: Sequence[str],
) -> dict[str, str]:
    value = item.get(key)
    if not isinstance(value, dict) or not all(
        isinstance(k, str) and isinstance(v, str) for k, v in value.items()
    ):
        raise _err(file, f"{desc}'s {key!r} must be a mapping of strings")
    missing = [k for k in required_keys if k not in value]
    if missing:
        raise _err(file, f"{desc}'s {key!r} is missing required key(s): {', '.join(missing)}")
    return dict(value)


# --- Per-file loading: entry list -> raw bytes + parsed YAML root --------------------


def _load_entry_list(path: Path) -> tuple[bytes, CommentedSeq]:
    raw = _read_bytes(path)
    try:
        doc = _YAML.load(raw)
    except Exception as exc:  # ruamel's parse failures aren't one exception type
        raise _err(path, f"is not valid YAML ({exc})") from exc
    if doc is None:
        doc = CommentedSeq()
    if not isinstance(doc, list):
        raise _err(path, "must be a YAML list of entries")
    for index, item in enumerate(doc):
        if not isinstance(item, dict):
            raise _err(path, f"entry at index {index} is not a mapping")
    # ruamel's round-trip loader always produces a CommentedSeq for a YAML list; the
    # isinstance(doc, list) check above only narrows mypy to the builtin `list` protocol.
    return raw, cast(CommentedSeq, doc)


def _load_entries[EntryT](
    file: Path,
    raw_items: Sequence[Mapping[str, object]],
    prefix: str,
    parser: Callable[[Path, str, Mapping[str, object]], EntryT],
) -> dict[str, EntryT]:
    """Build `{id: parsed entry}`, enforcing id presence, this file's required prefix, and
    within-file uniqueness. A prefix mismatch is a schema-conformance failure -- since
    every file only ever accepts its own prefix, this is what makes per-file uniqueness
    equal to the set's global uniqueness (artifacts.md)."""
    result: dict[str, EntryT] = {}
    for index, item in enumerate(raw_items):
        id_ = item.get("id")
        if not isinstance(id_, str) or not id_:
            raise _err(file, f"entry at index {index} is missing a non-empty string 'id'")
        if not id_.startswith(f"{prefix}-"):
            raise _err(
                file,
                f"id {id_!r} does not use the {prefix!r}- prefix required in {file.name}",
            )
        if id_ in result:
            raise _err(file, f"duplicate id {id_!r}")
        result[id_] = parser(file, id_, item)
    return result


def _load_coverage(
    file: Path, raw_items: Sequence[Mapping[str, object]]
) -> dict[str, CoverageEntry]:
    result: dict[str, CoverageEntry] = {}
    for index, item in enumerate(raw_items):
        fm_id = item.get("failure_mode_id")
        if not isinstance(fm_id, str) or not fm_id:
            raise _err(
                file,
                f"entry at index {index} is missing a non-empty string 'failure_mode_id'",
            )
        if fm_id in result:
            raise _err(file, f"duplicate coverage key (failure_mode_id) {fm_id!r}")
        desc = f"coverage entry for {fm_id!r}"
        result[fm_id] = CoverageEntry(
            failure_mode_id=fm_id,
            detecting_metric_ids=_str_list_field(file, item, "detecting_metric_ids", desc),
            metric_recommendation_ids=_str_list_field(
                file, item, "metric_recommendation_ids", desc
            ),
            alert_ids=_str_list_field(file, item, "alert_ids", desc),
        )
    return result


# --- Per-type field parsers -----------------------------------------------------------


def _parse_system_component(
    file: Path, id_: str, item: Mapping[str, object]
) -> SystemComponent:
    desc = f"system component {id_!r}"
    return SystemComponent(
        id=id_,
        name=_str_field(file, item, "name", desc),
        kind=_enum_field(file, item, "kind", desc, _COMPONENT_KINDS),
        description=_str_field(file, item, "description", desc),
        depends_on=_str_list_field(file, item, "depends_on", desc),
    )


def _parse_failure_mode(file: Path, id_: str, item: Mapping[str, object]) -> FailureMode:
    desc = f"failure mode {id_!r}"
    coverage_status = _enum_field(file, item, "coverage_status", desc, _COVERAGE_STATUSES)
    exclusion_reason = _optional_str_field(file, item, "exclusion_reason", desc)
    if coverage_status == "excluded" and not exclusion_reason:
        raise _err(file, f"{desc} is excluded but has no 'exclusion_reason'")
    return FailureMode(
        id=id_,
        title=_str_field(file, item, "title", desc),
        description=_str_field(file, item, "description", desc),
        severity=_enum_field(file, item, "severity", desc, _SEVERITIES),
        user_visible=_bool_field(file, item, "user_visible", desc),
        caused_by=_str_list_field(file, item, "caused_by", desc),
        coverage_status=coverage_status,
        exclusion_reason=exclusion_reason,
    )


def _parse_metric(file: Path, id_: str, item: Mapping[str, object]) -> Metric:
    desc = f"metric {id_!r}"
    return Metric(
        id=id_,
        name=_str_field(file, item, "name", desc),
        type=_enum_field(file, item, "type", desc, _METRIC_TYPES),
        labels=_str_list_field(file, item, "labels", desc),
        emitted_at=_str_list_field(file, item, "emitted_at", desc),
        description=_str_field(file, item, "description", desc),
    )


def _parse_metric_recommendation(
    file: Path, id_: str, item: Mapping[str, object]
) -> MetricRecommendation:
    desc = f"metric recommendation {id_!r}"
    kind = _enum_field(file, item, "kind", desc, _RECOMMENDATION_KINDS)
    metric_id = _optional_str_field(file, item, "metric_id", desc)
    if kind == "change" and metric_id is None:
        raise _err(file, f"{desc} has kind 'change' but no 'metric_id'")
    if kind == "new" and metric_id is not None:
        raise _err(file, f"{desc} has kind 'new' but specifies 'metric_id'")
    if metric_id is not None and not metric_id.startswith("mx-"):
        raise _err(file, f"{desc}'s metric_id {metric_id!r} does not use the 'mx-' prefix")
    return MetricRecommendation(
        id=id_,
        kind=kind,
        metric_id=metric_id,
        failure_mode_ids=_str_list_field(file, item, "failure_mode_ids", desc),
        rationale=_str_field(file, item, "rationale", desc),
        details=_str_field(file, item, "details", desc),
    )


def _parse_alert_recommendation(
    file: Path, id_: str, item: Mapping[str, object]
) -> AlertRecommendation:
    desc = f"alert recommendation {id_!r}"
    return AlertRecommendation(
        id=id_,
        name=_str_field(file, item, "name", desc),
        expr=_str_field(file, item, "expr", desc),
        for_duration=_str_field(file, item, "for_duration", desc),
        severity=_enum_field(file, item, "severity", desc, _SEVERITIES),
        failure_mode_ids=_str_list_field(file, item, "failure_mode_ids", desc),
        annotations=_str_map_field(file, item, "annotations", desc, ("summary", "description")),
    )


# --- Cross-entry structural checks ----------------------------------------------------


def _check_dangling_references(
    system_components: Mapping[str, SystemComponent],
    failure_modes: Mapping[str, FailureMode],
    metrics: Mapping[str, Metric],
    metric_recommendations: Mapping[str, MetricRecommendation],
    alert_recommendations: Mapping[str, AlertRecommendation],
    coverage: Mapping[str, CoverageEntry],
    files: Mapping[str, Path],
) -> None:
    """No reference to a nonexistent ID, from any entry (R19; deliberately not scoped to
    user-visible failure modes only, which is R3's narrower text -- R19 broadens it to
    every entry and every reference field)."""
    for component in system_components.values():
        for dep in component.depends_on:
            if dep not in system_components:
                raise _err(
                    files["system_components"],
                    f"system component {component.id!r} depends_on unknown id {dep!r}",
                )
    for fm in failure_modes.values():
        for cause in fm.caused_by:
            if cause not in failure_modes:
                raise _err(
                    files["failure_modes"],
                    f"failure mode {fm.id!r} caused_by unknown id {cause!r}",
                )
    for mr in metric_recommendations.values():
        if mr.metric_id is not None and mr.metric_id not in metrics:
            raise _err(
                files["metric_recommendations"],
                f"metric recommendation {mr.id!r} references unknown metric_id "
                f"{mr.metric_id!r}",
            )
        for fmid in mr.failure_mode_ids:
            if fmid not in failure_modes:
                raise _err(
                    files["metric_recommendations"],
                    f"metric recommendation {mr.id!r} references unknown failure_mode_id "
                    f"{fmid!r}",
                )
    for ar in alert_recommendations.values():
        for fmid in ar.failure_mode_ids:
            if fmid not in failure_modes:
                raise _err(
                    files["alert_recommendations"],
                    f"alert recommendation {ar.id!r} references unknown failure_mode_id "
                    f"{fmid!r}",
                )
    for entry in coverage.values():
        if entry.failure_mode_id not in failure_modes:
            raise _err(
                files["coverage"],
                f"coverage entry references unknown failure_mode_id "
                f"{entry.failure_mode_id!r}",
            )
        for mid in entry.detecting_metric_ids:
            if mid not in metrics:
                raise _err(
                    files["coverage"],
                    f"coverage entry for {entry.failure_mode_id!r} references unknown "
                    f"metric id {mid!r}",
                )
        for mrid in entry.metric_recommendation_ids:
            if mrid not in metric_recommendations:
                raise _err(
                    files["coverage"],
                    f"coverage entry for {entry.failure_mode_id!r} references unknown "
                    f"metric_recommendation id {mrid!r}",
                )
        for arid in entry.alert_ids:
            if arid not in alert_recommendations:
                raise _err(
                    files["coverage"],
                    f"coverage entry for {entry.failure_mode_id!r} references unknown "
                    f"alert id {arid!r}",
                )


def _check_acyclic(failure_modes: Mapping[str, FailureMode], file: Path) -> None:
    """The `caused_by` graph must be acyclic (R3/R19)."""
    unvisited, in_progress, done = 0, 1, 2
    state: dict[str, int] = dict.fromkeys(failure_modes, unvisited)

    def visit(fm_id: str, path: list[str]) -> None:
        state[fm_id] = in_progress
        path.append(fm_id)
        for cause in failure_modes[fm_id].caused_by:
            if state.get(cause) == in_progress:
                cycle = path[path.index(cause) :] + [cause]
                raise _err(file, f"caused_by cycle: {' -> '.join(cycle)}")
            if state.get(cause) == unvisited:
                visit(cause, path)
        path.pop()
        state[fm_id] = done

    for fm_id in failure_modes:
        if state[fm_id] == unvisited:
            visit(fm_id, [])


def _check_coverage_completeness(
    failure_modes: Mapping[str, FailureMode], coverage: Mapping[str, CoverageEntry], file: Path
) -> None:
    """Exactly one coverage entry per failure mode (duplicates are caught at parse time by
    `_load_coverage`; this catches the missing side)."""
    missing = sorted(set(failure_modes) - set(coverage))
    if missing:
        raise _err(file, f"missing coverage entry for failure mode(s): {', '.join(missing)}")


def _check_doc_headers(root: Path) -> None:
    """A file at a derived-doc path that exists but lacks the generated-file header is not
    Blare's to overwrite (R19) -- caught here as well as by `init_inspection`'s narrower,
    no-state-file scenario."""
    header_bytes = GENERATED_DOC_HEADER.encode()
    for entry_filename in _ENTRY_FILENAMES.values():
        doc_path = _doc_path(root, entry_filename)
        if not doc_path.is_file():
            continue
        raw = _read_bytes(doc_path)
        first_line = raw.split(b"\n", 1)[0]
        if first_line != header_bytes:
            raise _err(
                doc_path,
                "lacks the generated-file header; this file is not Blare's to overwrite",
            )


def _load_state(file: Path) -> tuple[str, int]:
    raw = _read_bytes(file)
    try:
        doc = _YAML.load(raw)
    except Exception as exc:  # ruamel's parse failures aren't one exception type
        raise _err(file, f"is not valid YAML ({exc})") from exc
    if not isinstance(doc, dict):
        raise _err(file, "must be a YAML mapping with 'analyzed_sha' and 'schema_version'")
    sha = doc.get("analyzed_sha")
    version = doc.get("schema_version")
    missing = []
    if not isinstance(sha, str) or not sha:
        missing.append("analyzed_sha")
    # bool is an int subclass in Python; excluded explicitly so `true`/`false` don't parse
    # as a schema version.
    if not isinstance(version, int) or isinstance(version, bool):
        missing.append("schema_version")
    if missing:
        raise _err(file, f"is missing required field(s): {', '.join(missing)}")
    assert isinstance(sha, str)
    assert isinstance(version, int)
    return sha, version


def _check_schema_version(file: Path, version: int) -> None:
    if version != CURRENT_SCHEMA_VERSION:
        raise SchemaVersionError(
            cause=(
                f"{file} records schema version {version}, but this Blare understands "
                f"version {CURRENT_SCHEMA_VERSION}"
            ),
            next_action=(
                "Run the Blare version that matches the recorded schema version, or "
                "delete .blare/ and re-run full analysis (this discards any "
                "hand-recorded content)."
            ),
        )


# --- Config and stack resolution (R23) -------------------------------------------------


def _config_error(path: Path, problem: str) -> ConfigError:
    return ConfigError(
        cause=f"{path} {problem}",
        next_action=(
            f"Edit {path} to set 'stack' to one of the supported values: "
            f"{', '.join(supported_stacks())}."
        ),
    )


def _resolve_stack(
    root: Path, *, missing_is_error: bool
) -> tuple[ObservabilityStack, str, bool]:
    """Resolve `config.yaml`'s stack (R23). `missing_is_error` is true only for `load` in
    update mode -- every other caller (`empty_set`, and `load` in analyze mode, R16
    re-analysis included) defaults in memory and lets the write primitives create the file.

    Returns the resolved stack handle, its name, and whether the file existed (write-side
    concern: an existing config is preserved byte-identically and never rewritten).
    """
    path = root / _CONFIG_FILENAME
    if not path.is_file():
        if missing_is_error:
            raise _config_error(path, "does not exist")
        return get_stack(_DEFAULT_STACK_NAME), _DEFAULT_STACK_NAME, False
    # Deliberately not `_read_bytes`: config.yaml is outside R19's scope (spec, Artifacts
    # -- "validated by R23" instead), so an unreadable config must raise `ConfigError`
    # with R23's own next_action, not the generic StructuralValidationError every other
    # canonical file's read failure raises.
    try:
        raw = path.read_bytes()
    except OSError as exc:
        raise _config_error(path, f"could not be read ({exc.strerror or exc})") from exc
    try:
        doc = _YAML.load(raw)
    except Exception as exc:  # ruamel's parse failures aren't one exception type
        raise _config_error(path, f"is not valid YAML ({exc})") from exc
    if not isinstance(doc, dict):
        raise _config_error(path, "does not define a 'stack' value")
    stack_name = doc.get("stack")
    if not isinstance(stack_name, str) or not stack_name.strip():
        raise _config_error(path, "does not define a 'stack' value")
    # An unsupported name propagates get_stack's own UnsupportedStackError unchanged
    # rather than being wrapped here. stack.py's own docstring frames this as artifacts
    # "attaching the file name when propagating it", but there is nothing left to
    # attach: get_stack's next_action already hardcodes the literal ".blare/config.yaml"
    # (the location is fixed, never configurable -- spec, Artifacts), so the message
    # already names the file and, via its cause, the supported values. Left unwrapped on
    # purpose rather than reformatted to use this function's own computed `path` (which
    # could be an absolute Path, unlike the stable relative literal get_stack uses).
    stack = get_stack(stack_name)
    return stack, stack_name, True


# --- Public interface ------------------------------------------------------------------


def state_exists(root: Path) -> bool:
    """Whether `state.yaml` exists -- the R1-vs-R16-vs-R17 mode dispatch."""
    return (root / _STATE_FILENAME).is_file()


def init_inspection(root: Path) -> None:
    """R1's inverse refusal: called only when `state_exists(root)` is false. Refuses,
    naming every offending file, when any canonical entry-based file or derived-doc-path
    file already exists -- an existing `config.yaml` alone never triggers this."""
    offending: list[Path] = []
    for filename in _ENTRY_FILENAMES.values():
        path = root / filename
        if path.exists():
            offending.append(path)
    for filename in _ENTRY_FILENAMES.values():
        doc_path = _doc_path(root, filename)
        if doc_path.exists():
            offending.append(doc_path)
    if offending:
        names = ", ".join(str(p) for p in offending)
        raise PreexistingFilesError(
            cause=f"no state file exists, but these files already do: {names}",
            next_action=(
                "Remove or relocate these files before running blare analyze, or restore "
                "the missing .blare/state.yaml if this codebase was analyzed before."
            ),
        )


def empty_set(root: Path) -> ArtifactSet:
    """The fresh R1 baseline: every entry map empty, no recorded analysis yet. Resolves
    `config.yaml` if present (honoring an unsupported stack's refusal) and defaults to
    Prometheus in memory when absent -- never calls `load`."""
    stack, stack_name, config_existed = _resolve_stack(root, missing_is_error=False)
    return ArtifactSet(
        system_components={},
        failure_modes={},
        metrics={},
        metric_recommendations={},
        alert_recommendations={},
        coverage={},
        analyzed_sha=None,
        schema_version=CURRENT_SCHEMA_VERSION,
        stack_name=stack_name,
        stack=stack,
        config_existed=config_existed,
        raw_bytes={},
        documents={},
    )


def load(root: Path, mode: RunMode) -> ArtifactSet:
    """Load and structurally validate the canonical YAML (R19), resolve config/stack
    (R23), and check the schema version (R24). Raises `StateMissingError` if `state.yaml`
    is absent (the R17 identity) -- the fresh R1 path never reaches here; it starts from
    `empty_set` instead."""
    state_path = root / _STATE_FILENAME
    if not state_exists(root):
        raise StateMissingError(
            cause=f"{state_path} does not exist",
            next_action="Run `blare analyze` first to produce the artifact set.",
        )

    analyzed_sha, schema_version = _load_state(state_path)
    _check_schema_version(state_path, schema_version)

    files: dict[str, Path] = {}
    raw_bytes: dict[str, bytes] = {}
    documents: dict[str, CommentedSeq] = {}
    raw_items: dict[str, CommentedSeq] = {}
    for key, filename in _ENTRY_FILENAMES.items():
        path = root / filename
        files[key] = path
        if not path.is_file():
            raise _err(
                path,
                "does not exist, but state.yaml does (entry files must be present when "
                "state exists)",
            )
        raw, items = _load_entry_list(path)
        raw_bytes[filename] = raw
        documents[filename] = items
        raw_items[key] = items

    system_components = _load_entries(
        files["system_components"], raw_items["system_components"], "sm", _parse_system_component
    )
    failure_modes = _load_entries(
        files["failure_modes"], raw_items["failure_modes"], "fm", _parse_failure_mode
    )
    metrics = _load_entries(files["metrics"], raw_items["metrics"], "mx", _parse_metric)
    metric_recommendations = _load_entries(
        files["metric_recommendations"],
        raw_items["metric_recommendations"],
        "mr",
        _parse_metric_recommendation,
    )
    alert_recommendations = _load_entries(
        files["alert_recommendations"],
        raw_items["alert_recommendations"],
        "ar",
        _parse_alert_recommendation,
    )
    coverage = _load_coverage(files["coverage"], raw_items["coverage"])

    _check_dangling_references(
        system_components,
        failure_modes,
        metrics,
        metric_recommendations,
        alert_recommendations,
        coverage,
        files,
    )
    _check_acyclic(failure_modes, files["failure_modes"])
    _check_coverage_completeness(failure_modes, coverage, files["coverage"])
    _check_doc_headers(root)

    raw_bytes[_STATE_FILENAME] = _read_bytes(state_path)
    stack, stack_name, config_existed = _resolve_stack(
        root, missing_is_error=(mode is RunMode.UPDATE)
    )

    return ArtifactSet(
        system_components=system_components,
        failure_modes=failure_modes,
        metrics=metrics,
        metric_recommendations=metric_recommendations,
        alert_recommendations=alert_recommendations,
        coverage=coverage,
        analyzed_sha=analyzed_sha,
        schema_version=schema_version,
        stack_name=stack_name,
        stack=stack,
        config_existed=config_existed,
        raw_bytes=raw_bytes,
        documents=documents,
    )


def semantic_violations(s: ArtifactSet) -> list[Violation]:
    """R4-R5 in full, plus the excluded-empty-sets property (artifacts.md). Never raises
    for a violating set -- a violating set still loads; this seeds the R18 affected-phase
    queue and drives system-originated amendments. A misbehaving stack (one whose
    `validate_expression` raises rather than returning a verdict) is treated as an
    invalid-expression violation rather than allowed to crash the check."""
    violations: list[Violation] = []

    coverage_fms_by_alert: dict[str, set[str]] = {}
    for cov_entry in s.coverage.values():
        for arid in cov_entry.alert_ids:
            coverage_fms_by_alert.setdefault(arid, set()).add(cov_entry.failure_mode_id)

    for fm in s.failure_modes.values():
        entry = s.coverage.get(fm.id)
        # `load` guarantees a coverage entry for every failure mode; `entry` is only ever
        # None here for a hand-built ArtifactSet in a test that bypasses that guarantee,
        # in which case there is nothing to check for this failure mode.
        if entry is None:
            continue
        if fm.coverage_status == "excluded":
            metric_side_dirty = bool(
                entry.detecting_metric_ids or entry.metric_recommendation_ids
            ) or any(fm.id in mr.failure_mode_ids for mr in s.metric_recommendations.values())
            if metric_side_dirty:
                violations.append(
                    Violation(ViolationKind.EXCLUDED_WITH_METRIC_COVERAGE, (fm.id,))
                )
            alert_side_dirty = bool(entry.alert_ids) or any(
                fm.id in ar.failure_mode_ids for ar in s.alert_recommendations.values()
            )
            if alert_side_dirty:
                violations.append(
                    Violation(ViolationKind.EXCLUDED_WITH_ALERT_COVERAGE, (fm.id,))
                )
        elif not entry.alert_ids:
            violations.append(Violation(ViolationKind.UNMAPPED_FAILURE_MODE, (fm.id,)))

    for mr in s.metric_recommendations.values():
        if not mr.failure_mode_ids:
            violations.append(
                Violation(ViolationKind.EMPTY_LINKAGE_METRIC_RECOMMENDATION, (mr.id,))
            )

    for ar in s.alert_recommendations.values():
        if not ar.failure_mode_ids:
            violations.append(
                Violation(ViolationKind.EMPTY_LINKAGE_ALERT_RECOMMENDATION, (ar.id,))
            )

        try:
            verdict = s.stack.validate_expression(ar.expr)
        except Exception:
            # Defense-in-depth (artifacts.md's failure-mode test plan): a misbehaving
            # stack must not crash the run.
            violations.append(Violation(ViolationKind.INVALID_EXPRESSION, (ar.id,)))
        else:
            if not verdict.ok:
                violations.append(Violation(ViolationKind.INVALID_EXPRESSION, (ar.id,)))

        ranks = [
            _SEVERITY_RANK[s.failure_modes[fmid].severity]
            for fmid in ar.failure_mode_ids
            if fmid in s.failure_modes and s.failure_modes[fmid].severity in _SEVERITY_RANK
        ]
        if ranks:
            max_rank = max(ranks)
            if _SEVERITY_RANK.get(ar.severity, 0) < max_rank:
                violations.append(Violation(ViolationKind.ALERT_SEVERITY_BELOW_MAX, (ar.id,)))

        expected_fms = set(ar.failure_mode_ids)
        actual_fms = coverage_fms_by_alert.get(ar.id, set())
        if expected_fms != actual_fms:
            violations.append(Violation(ViolationKind.LINKAGE_INCONSISTENCY, (ar.id,)))

    return violations


def gap_counts(s: ArtifactSet) -> GapSummary:
    """Non-excluded failure modes split by coverage status (R13)."""
    alertable = metric_gap = excluded = 0
    for fm in s.failure_modes.values():
        if fm.coverage_status == "alertable":
            alertable += 1
        elif fm.coverage_status == "metric-gap":
            metric_gap += 1
        else:
            excluded += 1
    return GapSummary(alertable=alertable, metric_gap=metric_gap, excluded=excluded)


__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "GENERATED_DOC_HEADER",
    "StructuralValidationError",
    "StateMissingError",
    "PreexistingFilesError",
    "ConfigError",
    "SchemaVersionError",
    "SystemComponent",
    "FailureMode",
    "Metric",
    "MetricRecommendation",
    "AlertRecommendation",
    "CoverageEntry",
    "GapSummary",
    "ArtifactSet",
    "state_exists",
    "init_inspection",
    "empty_set",
    "load",
    "semantic_violations",
    "gap_counts",
]
