"""Everything under `.blare/` (architecture: no other module touches it): schemas,
the three validation tiers (R19 structural, per-batch content, R4-R5 semantic), surgical
edit application, deterministic rendering, ordered writing, state and config (R23, R24).

T1.4 built the read side: `state_exists`, `init_inspection`, `empty_set`, `load`,
`semantic_violations`, `gap_counts`. This task (T1.5) adds the write side: `batch_check`,
`apply`, `referencing_phases`, `render_docs`, `raw_bytes_match`, and the three write
primitives (`write_entries_and_config`, `write_docs`, `write_state`), per
`engineering/modules/artifacts.md`.

Throughout this module, `root` names the `.blare/` directory itself (the layout tree in
`engineering/architecture.md`'s "Artifact file layout" section is rooted there) -- not
the target repo's root. The orchestrator is expected to pass `repo_root / ".blare"`.
"""

from __future__ import annotations

import copy
import io
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq

from blare.model import (
    BatchVerdict,
    BlareError,
    Edit,
    EditBatch,
    EditOp,
    Phase,
    RunMode,
    Violation,
    ViolationKind,
)
from blare.stack import AlertRuleInput, ObservabilityStack, get_stack, supported_stacks

CURRENT_SCHEMA_VERSION = 1

# The first line every derived doc (docs/*.md) must carry (spec, Artifacts: "generated --
# do not edit"). Exact wording is this module's own choice -- nothing upstream fixes it --
# but it must stay stable: `load` checks it on every read, and T1.5's rendering (out of
# this task's scope) must produce it verbatim.
GENERATED_DOC_HEADER = (
    "<!-- Generated by blare. Do not edit -- changes are overwritten on the next run. -->"
)

_STATE_FILENAME = "state.yaml"
_CONFIG_FILENAME = "config.yaml"
_DOCS_DIRNAME = "docs"
_DEFAULT_STACK_NAME = "prometheus"

# Canonical entry-based files, keyed by the ArtifactSet field they populate, in the
# architecture's layout order. Every value here is also a "path derived docs use" once
# its basename is run through `_doc_path`.
_ENTRY_FILENAMES: dict[str, str] = {
    "system_components": "system-map.yaml",
    "failure_modes": "failure-modes.yaml",
    "metrics": "metrics.yaml",
    "metric_recommendations": "metric-recommendations.yaml",
    "alert_recommendations": "alert-recommendations.yaml",
    "coverage": "coverage.yaml",
}

_COMPONENT_KINDS = (
    "service",
    "worker",
    "job",
    "external-dependency",
    "datastore",
    "entrypoint",
)
_SEVERITIES = ("critical", "warning")
_COVERAGE_STATUSES = ("alertable", "metric-gap", "excluded")
_METRIC_TYPES = ("counter", "gauge", "histogram", "summary")
_RECOMMENDATION_KINDS = ("new", "change")

_SEVERITY_RANK: dict[str, int] = {"warning": 0, "critical": 1}

# The canonical YAML set (spec, Artifacts: "entry-based artifacts plus state"), the R20
# write-time re-check's comparison scope -- config.yaml is deliberately excluded (a
# pre-existing config is legitimate on the fresh path and is never rewritten by Blare).
_CANONICAL_YAML_FILENAMES: tuple[str, ...] = (*_ENTRY_FILENAMES.values(), _STATE_FILENAME)

# One shared round-trip YAML (de)serializer. Round-trip mode (not safe/rt-lite) is what
# lets T1.5 preserve hand-formatting on entries an edit batch never touches (R9/R16); this
# task only reads, but loads through the same instance so the parsed representation is
# exactly what T1.5 builds its surgical writes on.
_YAML = YAML(typ="rt")
_YAML.preserve_quotes = True


class StructuralValidationError(BlareError):
    """One of R19's structural rules failed on load: schema conformance, a dangling
    reference, a `caused_by` cycle, a missing required field, a missing exclusion reason,
    a missing or duplicate coverage entry, an unparseable or incomplete state file, an
    unreadable or missing entry file, or a headerless file at a derived-doc path. Cause
    names the file and the exact problem, verbatim (R13)."""


class StateMissingError(BlareError):
    """`load` (or `state_exists`'s caller) found no `state.yaml` (R17's identity): `blare
    update` needs a prior `blare analyze`. Message names `blare analyze` as the fix."""


class PreexistingFilesError(BlareError):
    """`init_inspection` found canonical entry-based files or derived-doc-path files with
    no state file present (R1's inverse refusal). An existing `config.yaml` alone never
    triggers this. Cause names every offending file."""


class ConfigError(BlareError):
    """`config.yaml` is missing (update mode only, R23), unparseable, or parses without a
    usable `stack` value (empty/null document included). Names the file and the supported
    stack values. An *unsupported* stack name is not this error: it propagates stack's own
    `UnsupportedStackError` unchanged, which already names the file's fixed path (it is
    never configurable, spec's Artifacts section) and the supported values."""


class SchemaVersionError(BlareError):
    """`state.yaml`'s `schema_version` does not match `CURRENT_SCHEMA_VERSION` (R24).
    Cause names both versions; distinct from `StructuralValidationError` since the
    recovery (run the matching Blare version, or discard and re-analyze) differs from a
    plain data-shape fix."""


class WriteError(BlareError):
    """A write primitive (T1.5) failed partway through -- the underlying filesystem
    operation raised (R20's crash case). Cause names the failing file; next_action
    points at git as the recovery, since Blare never commits and `write_state` -- the
    last primitive in the orchestrator's write order -- has not yet run, so the old
    analyzed SHA still matches whatever landed on disk (architecture, Write path)."""


# --- Entry types -------------------------------------------------------------------


@dataclass(frozen=True)
class SystemComponent:
    """One system-map entry (`system-map.yaml`, phase 1). `kind` is one of
    `_COMPONENT_KINDS`; `depends_on` names other `sm-` ids."""

    id: str
    name: str
    kind: str
    description: str
    depends_on: tuple[str, ...]


@dataclass(frozen=True)
class FailureMode:
    """One failure-mode entry (`failure-modes.yaml`, phase 2). `severity` is one of
    `_SEVERITIES`; `coverage_status` is one of `_COVERAGE_STATUSES`; `caused_by` names
    other `fm-` ids (the causal graph, R3); `exclusion_reason` is required iff
    `coverage_status == "excluded"`."""

    id: str
    title: str
    description: str
    severity: str
    user_visible: bool
    caused_by: tuple[str, ...]
    coverage_status: str
    exclusion_reason: str | None


@dataclass(frozen=True)
class Metric:
    """One implemented-metric entry (`metrics.yaml`, phase 3). `type` is one of
    `_METRIC_TYPES`; `emitted_at` is a list of `path:line` locations."""

    id: str
    name: str
    type: str
    labels: tuple[str, ...]
    emitted_at: tuple[str, ...]
    description: str


@dataclass(frozen=True)
class MetricRecommendation:
    """One metric-change recommendation (`metric-recommendations.yaml`, phase 3). `kind`
    is `new` or `change`; `metric_id` (an `mx-` id) is required iff `kind == "change"` and
    forbidden otherwise. `failure_mode_ids` non-emptiness is a semantic invariant (R5), not
    schema."""

    id: str
    kind: str
    metric_id: str | None
    failure_mode_ids: tuple[str, ...]
    rationale: str
    details: str


@dataclass(frozen=True)
class AlertRecommendation:
    """One alert recommendation (`alert-recommendations.yaml`, phase 4). `severity` is one
    of `_SEVERITIES`; `annotations` must carry `summary` and `description` keys (schema);
    `failure_mode_ids` non-emptiness and `expr` validity are semantic invariants (R4-R5),
    not schema."""

    id: str
    name: str
    expr: str
    for_duration: str
    severity: str
    failure_mode_ids: tuple[str, ...]
    annotations: Mapping[str, str]


@dataclass(frozen=True)
class CoverageEntry:
    """One coverage-mapping entry (`coverage.yaml`, spanning phases 3-4). Keyed by
    `failure_mode_id` -- the one exception to the `<prefix>-<slug>` id scheme (artifacts.md)
    -- with exactly one entry per failure mode, excluded ones included."""

    failure_mode_id: str
    detecting_metric_ids: tuple[str, ...]
    metric_recommendation_ids: tuple[str, ...]
    alert_ids: tuple[str, ...]


@dataclass(frozen=True)
class GapSummary:
    """Non-excluded failure modes split by coverage status (R13's gap count); `excluded`
    is carried for context only -- an excluded failure mode is never a gap (Terms)."""

    alertable: int
    metric_gap: int
    excluded: int


@dataclass
class ArtifactSet:
    """The in-memory whole artifact set (architecture: `artifacts` owns everything under
    `.blare/`): typed entry maps, the state fields, the resolved stack handle, and the
    loaded representation T1.5 builds surgical writes on.

    `raw_bytes` is keyed by canonical filename and covers the entry files plus
    `state.yaml` (the R20 comparison baseline, `raw_bytes_match`) -- `config.yaml` is
    excluded, matching R20's own carve-out (artifacts.md: "config.yaml is outside the
    comparison"). `documents` is keyed by entry-file filename only (state.yaml is a
    mapping of two scalar fields, always rewritten wholesale by `write_state` rather than
    surgically merged, so there is no round-trip document worth retaining for it): each
    entry file's round-trip-parsed `CommentedSeq`, the list T1.5's surgical edit
    application locates entries in without disturbing untouched ones' formatting. Both
    are empty on the fresh `empty_set` baseline, matching `init_inspection` having
    verified nothing was at those paths.

    A later `apply` (T1.5) must return a new `ArtifactSet` rather than mutate this one in
    place -- the entry maps and `raw_bytes`/`documents` dicts here are plain, mutable
    containers only because dataclasses do not enforce immutability of their contents;
    `apply`'s purity is a caller discipline this module does not currently enforce
    structurally.
    """

    system_components: dict[str, SystemComponent]
    failure_modes: dict[str, FailureMode]
    metrics: dict[str, Metric]
    metric_recommendations: dict[str, MetricRecommendation]
    alert_recommendations: dict[str, AlertRecommendation]
    coverage: dict[str, CoverageEntry]
    analyzed_sha: str | None
    schema_version: int
    stack_name: str
    stack: ObservabilityStack
    config_existed: bool
    raw_bytes: dict[str, bytes]
    documents: dict[str, CommentedSeq]


@dataclass(frozen=True)
class WriteReport:
    """One write primitive's outcome (artifacts.md, Failure visibility): every canonical
    path it wrote (content changed, or a fresh run creating it for the first time) and
    every one it left alone (an unchanged entry file, or an existing `config.yaml`).
    Paths are absolute (`root`-joined), matching the style every other error in this
    module already names files in. A primitive that fails partway raises `WriteError`
    naming the failing file instead of returning; the reports already returned by
    *earlier* primitives in the orchestrator's write order are the partial-write record
    (architecture, Write path)."""

    written: tuple[Path, ...]
    skipped: tuple[Path, ...]


# --- Small parsing helpers -----------------------------------------------------------


def _err(file: Path, problem: str) -> StructuralValidationError:
    return StructuralValidationError(
        cause=f"{file}: {problem}",
        next_action=(
            "Fix the file by hand (see the problem above), or restore .blare/ from git, "
            "then re-run blare."
        ),
    )


def _doc_path(root: Path, entry_filename: str) -> Path:
    return root / _DOCS_DIRNAME / f"{Path(entry_filename).stem}.md"


def _read_bytes(path: Path) -> bytes:
    try:
        return path.read_bytes()
    except OSError as exc:
        raise _err(path, f"could not be read ({exc.strerror or exc})") from exc


def _str_field(file: Path, item: Mapping[str, object], key: str, desc: str) -> str:
    value = item.get(key)
    if not isinstance(value, str) or not value:
        raise _err(file, f"{desc} is missing a non-empty string {key!r}")
    return value


def _optional_str_field(
    file: Path, item: Mapping[str, object], key: str, desc: str
) -> str | None:
    if key not in item or item[key] is None:
        return None
    value = item[key]
    if not isinstance(value, str):
        raise _err(file, f"{desc}'s {key!r} must be a string")
    return value


def _bool_field(file: Path, item: Mapping[str, object], key: str, desc: str) -> bool:
    value = item.get(key)
    if not isinstance(value, bool):
        raise _err(file, f"{desc} is missing a boolean {key!r}")
    return value


def _enum_field(
    file: Path, item: Mapping[str, object], key: str, desc: str, allowed: Sequence[str]
) -> str:
    value = item.get(key)
    if value not in allowed:
        raise _err(file, f"{desc}'s {key!r} must be one of {list(allowed)}, got {value!r}")
    assert isinstance(value, str)  # narrowed by the membership check above
    return value


def _str_list_field(
    file: Path, item: Mapping[str, object], key: str, desc: str
) -> tuple[str, ...]:
    value = item.get(key, [])
    if value is None:
        value = []
    if not isinstance(value, list) or not all(isinstance(v, str) for v in value):
        raise _err(file, f"{desc}'s {key!r} must be a list of strings")
    return tuple(value)


def _str_map_field(
    file: Path,
    item: Mapping[str, object],
    key: str,
    desc: str,
    required_keys: Sequence[str],
) -> dict[str, str]:
    value = item.get(key)
    if not isinstance(value, dict) or not all(
        isinstance(k, str) and isinstance(v, str) for k, v in value.items()
    ):
        raise _err(file, f"{desc}'s {key!r} must be a mapping of strings")
    missing = [k for k in required_keys if k not in value]
    if missing:
        raise _err(file, f"{desc}'s {key!r} is missing required key(s): {', '.join(missing)}")
    return dict(value)


# --- Per-file loading: entry list -> raw bytes + parsed YAML root --------------------


def _load_entry_list(path: Path) -> tuple[bytes, CommentedSeq]:
    raw = _read_bytes(path)
    try:
        doc = _YAML.load(raw)
    except Exception as exc:  # ruamel's parse failures aren't one exception type
        raise _err(path, f"is not valid YAML ({exc})") from exc
    if doc is None:
        doc = CommentedSeq()
    if not isinstance(doc, list):
        raise _err(path, "must be a YAML list of entries")
    for index, item in enumerate(doc):
        if not isinstance(item, dict):
            raise _err(path, f"entry at index {index} is not a mapping")
    # ruamel's round-trip loader always produces a CommentedSeq for a YAML list; the
    # isinstance(doc, list) check above only narrows mypy to the builtin `list` protocol.
    return raw, cast(CommentedSeq, doc)


def _extract_prefixed_id(
    file: Path, item: Mapping[str, object], prefix: str, index: int | None = None
) -> str:
    """Extract and validate an entry's `id`: non-empty string, carrying `prefix`'s
    required `<prefix>-` form. Shared by `_load_entries` (load-time, `index` given for
    the error message) and T1.5's batch-check/apply (no `index`, since a batch edit's
    payload isn't drawn from an indexed list) -- the one place this rule is enforced,
    so the two call sites can never drift (artifacts.md: "a prefix in the wrong file is
    a schema-conformance failure")."""
    id_ = item.get("id")
    if not isinstance(id_, str) or not id_:
        loc = f"entry at index {index}" if index is not None else "entry"
        raise _err(file, f"{loc} is missing a non-empty string 'id'")
    if not id_.startswith(f"{prefix}-"):
        raise _err(
            file,
            f"id {id_!r} does not use the {prefix!r}- prefix required in {file.name}",
        )
    return id_


def _load_entries[EntryT](
    file: Path,
    raw_items: Sequence[Mapping[str, object]],
    prefix: str,
    parser: Callable[[Path, str, Mapping[str, object]], EntryT],
) -> dict[str, EntryT]:
    """Build `{id: parsed entry}`, enforcing id presence, this file's required prefix, and
    within-file uniqueness. A prefix mismatch is a schema-conformance failure -- since
    every file only ever accepts its own prefix, this is what makes per-file uniqueness
    equal to the set's global uniqueness (artifacts.md)."""
    result: dict[str, EntryT] = {}
    for index, item in enumerate(raw_items):
        id_ = _extract_prefixed_id(file, item, prefix, index)
        if id_ in result:
            raise _err(file, f"duplicate id {id_!r}")
        result[id_] = parser(file, id_, item)
    return result


def _extract_coverage_key(file: Path, item: Mapping[str, object], index: int | None = None) -> str:
    """Extract and validate a coverage entry's `failure_mode_id` -- the one entry type
    keyed by something other than a prefixed `id` (artifacts.md). Shared by
    `_load_coverage` and T1.5's batch-check/apply, same reasoning as
    `_extract_prefixed_id`."""
    fm_id = item.get("failure_mode_id")
    if not isinstance(fm_id, str) or not fm_id:
        loc = f"entry at index {index}" if index is not None else "entry"
        raise _err(file, f"{loc} is missing a non-empty string 'failure_mode_id'")
    return fm_id


def _parse_coverage_entry(file: Path, fm_id: str, item: Mapping[str, object]) -> CoverageEntry:
    desc = f"coverage entry for {fm_id!r}"
    return CoverageEntry(
        failure_mode_id=fm_id,
        detecting_metric_ids=_str_list_field(file, item, "detecting_metric_ids", desc),
        metric_recommendation_ids=_str_list_field(file, item, "metric_recommendation_ids", desc),
        alert_ids=_str_list_field(file, item, "alert_ids", desc),
    )


def _load_coverage(
    file: Path, raw_items: Sequence[Mapping[str, object]]
) -> dict[str, CoverageEntry]:
    result: dict[str, CoverageEntry] = {}
    for index, item in enumerate(raw_items):
        fm_id = _extract_coverage_key(file, item, index)
        if fm_id in result:
            raise _err(file, f"duplicate coverage key (failure_mode_id) {fm_id!r}")
        result[fm_id] = _parse_coverage_entry(file, fm_id, item)
    return result


# --- Per-type field parsers -----------------------------------------------------------


def _parse_system_component(
    file: Path, id_: str, item: Mapping[str, object]
) -> SystemComponent:
    desc = f"system component {id_!r}"
    return SystemComponent(
        id=id_,
        name=_str_field(file, item, "name", desc),
        kind=_enum_field(file, item, "kind", desc, _COMPONENT_KINDS),
        description=_str_field(file, item, "description", desc),
        depends_on=_str_list_field(file, item, "depends_on", desc),
    )


def _parse_failure_mode(file: Path, id_: str, item: Mapping[str, object]) -> FailureMode:
    desc = f"failure mode {id_!r}"
    coverage_status = _enum_field(file, item, "coverage_status", desc, _COVERAGE_STATUSES)
    exclusion_reason = _optional_str_field(file, item, "exclusion_reason", desc)
    if coverage_status == "excluded" and not exclusion_reason:
        raise _err(file, f"{desc} is excluded but has no 'exclusion_reason'")
    return FailureMode(
        id=id_,
        title=_str_field(file, item, "title", desc),
        description=_str_field(file, item, "description", desc),
        severity=_enum_field(file, item, "severity", desc, _SEVERITIES),
        user_visible=_bool_field(file, item, "user_visible", desc),
        caused_by=_str_list_field(file, item, "caused_by", desc),
        coverage_status=coverage_status,
        exclusion_reason=exclusion_reason,
    )


def _parse_metric(file: Path, id_: str, item: Mapping[str, object]) -> Metric:
    desc = f"metric {id_!r}"
    return Metric(
        id=id_,
        name=_str_field(file, item, "name", desc),
        type=_enum_field(file, item, "type", desc, _METRIC_TYPES),
        labels=_str_list_field(file, item, "labels", desc),
        emitted_at=_str_list_field(file, item, "emitted_at", desc),
        description=_str_field(file, item, "description", desc),
    )


def _parse_metric_recommendation(
    file: Path, id_: str, item: Mapping[str, object]
) -> MetricRecommendation:
    desc = f"metric recommendation {id_!r}"
    kind = _enum_field(file, item, "kind", desc, _RECOMMENDATION_KINDS)
    metric_id = _optional_str_field(file, item, "metric_id", desc)
    if kind == "change" and metric_id is None:
        raise _err(file, f"{desc} has kind 'change' but no 'metric_id'")
    if kind == "new" and metric_id is not None:
        raise _err(file, f"{desc} has kind 'new' but specifies 'metric_id'")
    if metric_id is not None and not metric_id.startswith("mx-"):
        raise _err(file, f"{desc}'s metric_id {metric_id!r} does not use the 'mx-' prefix")
    return MetricRecommendation(
        id=id_,
        kind=kind,
        metric_id=metric_id,
        failure_mode_ids=_str_list_field(file, item, "failure_mode_ids", desc),
        rationale=_str_field(file, item, "rationale", desc),
        details=_str_field(file, item, "details", desc),
    )


def _parse_alert_recommendation(
    file: Path, id_: str, item: Mapping[str, object]
) -> AlertRecommendation:
    desc = f"alert recommendation {id_!r}"
    return AlertRecommendation(
        id=id_,
        name=_str_field(file, item, "name", desc),
        expr=_str_field(file, item, "expr", desc),
        for_duration=_str_field(file, item, "for_duration", desc),
        severity=_enum_field(file, item, "severity", desc, _SEVERITIES),
        failure_mode_ids=_str_list_field(file, item, "failure_mode_ids", desc),
        annotations=_str_map_field(file, item, "annotations", desc, ("summary", "description")),
    )


# --- Per-type field serializers (T1.5: the parsers' inverse, for surgical writing) ----


def _serialize_system_component(c: SystemComponent) -> dict[str, object]:
    return {
        "id": c.id,
        "name": c.name,
        "kind": c.kind,
        "description": c.description,
        "depends_on": list(c.depends_on),
    }


def _serialize_failure_mode(fm: FailureMode) -> dict[str, object]:
    fields: dict[str, object] = {
        "id": fm.id,
        "title": fm.title,
        "description": fm.description,
        "severity": fm.severity,
        "user_visible": fm.user_visible,
        "caused_by": list(fm.caused_by),
        "coverage_status": fm.coverage_status,
    }
    if fm.exclusion_reason is not None:
        fields["exclusion_reason"] = fm.exclusion_reason
    return fields


def _serialize_metric(m: Metric) -> dict[str, object]:
    return {
        "id": m.id,
        "name": m.name,
        "type": m.type,
        "labels": list(m.labels),
        "emitted_at": list(m.emitted_at),
        "description": m.description,
    }


def _serialize_metric_recommendation(mr: MetricRecommendation) -> dict[str, object]:
    fields: dict[str, object] = {"id": mr.id, "kind": mr.kind}
    if mr.metric_id is not None:
        fields["metric_id"] = mr.metric_id
    fields["failure_mode_ids"] = list(mr.failure_mode_ids)
    fields["rationale"] = mr.rationale
    fields["details"] = mr.details
    return fields


def _serialize_alert_recommendation(ar: AlertRecommendation) -> dict[str, object]:
    return {
        "id": ar.id,
        "name": ar.name,
        "expr": ar.expr,
        "for_duration": ar.for_duration,
        "severity": ar.severity,
        "failure_mode_ids": list(ar.failure_mode_ids),
        "annotations": dict(ar.annotations),
    }


def _serialize_coverage(c: CoverageEntry) -> dict[str, object]:
    return {
        "failure_mode_id": c.failure_mode_id,
        "detecting_metric_ids": list(c.detecting_metric_ids),
        "metric_recommendation_ids": list(c.metric_recommendation_ids),
        "alert_ids": list(c.alert_ids),
    }


# --- Entry-type registry (T1.5: one source of truth for batch_check/apply/write) -----


@dataclass(frozen=True)
class _TypeSpec:
    """Everything the write side needs to know about one entry-based file, keyed by the
    same `ArtifactSet` field name used throughout this module (`_ENTRY_FILENAMES`'s
    keys) -- that string is also `Edit.entry_type`'s contract (implementation detail,
    artifacts.md's decisions section). `prefix`/`phase` are `None` for `"coverage"`,
    the one entry type with no `id` prefix and no single owning phase (it spans phases
    3-4 by side, artifacts.md)."""

    filename: str
    id_key: str
    prefix: str | None
    phase: Phase | None
    parser: Callable[[Path, str, Mapping[str, object]], object]
    serializer: Callable[[Any], dict[str, object]]


_TYPE_SPECS: dict[str, _TypeSpec] = {
    "system_components": _TypeSpec(
        "system-map.yaml", "id", "sm", Phase.SYSTEM_MAP,
        _parse_system_component, _serialize_system_component,
    ),
    "failure_modes": _TypeSpec(
        "failure-modes.yaml", "id", "fm", Phase.FAILURE_MODES,
        _parse_failure_mode, _serialize_failure_mode,
    ),
    "metrics": _TypeSpec(
        "metrics.yaml", "id", "mx", Phase.METRIC_COVERAGE,
        _parse_metric, _serialize_metric,
    ),
    "metric_recommendations": _TypeSpec(
        "metric-recommendations.yaml", "id", "mr", Phase.METRIC_COVERAGE,
        _parse_metric_recommendation, _serialize_metric_recommendation,
    ),
    "alert_recommendations": _TypeSpec(
        "alert-recommendations.yaml", "id", "ar", Phase.ALERT_RECOMMENDATIONS,
        _parse_alert_recommendation, _serialize_alert_recommendation,
    ),
    "coverage": _TypeSpec(
        "coverage.yaml", "failure_mode_id", None, None,
        _parse_coverage_entry, _serialize_coverage,
    ),
}


# --- Cross-entry structural checks ----------------------------------------------------


def _check_dangling_references(
    system_components: Mapping[str, SystemComponent],
    failure_modes: Mapping[str, FailureMode],
    metrics: Mapping[str, Metric],
    metric_recommendations: Mapping[str, MetricRecommendation],
    alert_recommendations: Mapping[str, AlertRecommendation],
    coverage: Mapping[str, CoverageEntry],
    files: Mapping[str, Path],
) -> None:
    """No reference to a nonexistent ID, from any entry (R19; deliberately not scoped to
    user-visible failure modes only, which is R3's narrower text -- R19 broadens it to
    every entry and every reference field)."""
    for component in system_components.values():
        for dep in component.depends_on:
            if dep not in system_components:
                raise _err(
                    files["system_components"],
                    f"system component {component.id!r} depends_on unknown id {dep!r}",
                )
    for fm in failure_modes.values():
        for cause in fm.caused_by:
            if cause not in failure_modes:
                raise _err(
                    files["failure_modes"],
                    f"failure mode {fm.id!r} caused_by unknown id {cause!r}",
                )
    for mr in metric_recommendations.values():
        if mr.metric_id is not None and mr.metric_id not in metrics:
            raise _err(
                files["metric_recommendations"],
                f"metric recommendation {mr.id!r} references unknown metric_id "
                f"{mr.metric_id!r}",
            )
        for fmid in mr.failure_mode_ids:
            if fmid not in failure_modes:
                raise _err(
                    files["metric_recommendations"],
                    f"metric recommendation {mr.id!r} references unknown failure_mode_id "
                    f"{fmid!r}",
                )
    for ar in alert_recommendations.values():
        for fmid in ar.failure_mode_ids:
            if fmid not in failure_modes:
                raise _err(
                    files["alert_recommendations"],
                    f"alert recommendation {ar.id!r} references unknown failure_mode_id "
                    f"{fmid!r}",
                )
    for entry in coverage.values():
        if entry.failure_mode_id not in failure_modes:
            raise _err(
                files["coverage"],
                f"coverage entry references unknown failure_mode_id "
                f"{entry.failure_mode_id!r}",
            )
        for mid in entry.detecting_metric_ids:
            if mid not in metrics:
                raise _err(
                    files["coverage"],
                    f"coverage entry for {entry.failure_mode_id!r} references unknown "
                    f"metric id {mid!r}",
                )
        for mrid in entry.metric_recommendation_ids:
            if mrid not in metric_recommendations:
                raise _err(
                    files["coverage"],
                    f"coverage entry for {entry.failure_mode_id!r} references unknown "
                    f"metric_recommendation id {mrid!r}",
                )
        for arid in entry.alert_ids:
            if arid not in alert_recommendations:
                raise _err(
                    files["coverage"],
                    f"coverage entry for {entry.failure_mode_id!r} references unknown "
                    f"alert id {arid!r}",
                )


def _check_acyclic(failure_modes: Mapping[str, FailureMode], file: Path) -> None:
    """The `caused_by` graph must be acyclic (R3/R19)."""
    unvisited, in_progress, done = 0, 1, 2
    state: dict[str, int] = dict.fromkeys(failure_modes, unvisited)

    def visit(fm_id: str, path: list[str]) -> None:
        state[fm_id] = in_progress
        path.append(fm_id)
        for cause in failure_modes[fm_id].caused_by:
            if state.get(cause) == in_progress:
                cycle = path[path.index(cause) :] + [cause]
                raise _err(file, f"caused_by cycle: {' -> '.join(cycle)}")
            if state.get(cause) == unvisited:
                visit(cause, path)
        path.pop()
        state[fm_id] = done

    for fm_id in failure_modes:
        if state[fm_id] == unvisited:
            visit(fm_id, [])


def _check_coverage_completeness(
    failure_modes: Mapping[str, FailureMode], coverage: Mapping[str, CoverageEntry], file: Path
) -> None:
    """Exactly one coverage entry per failure mode (duplicates are caught at parse time by
    `_load_coverage`; this catches the missing side)."""
    missing = sorted(set(failure_modes) - set(coverage))
    if missing:
        raise _err(file, f"missing coverage entry for failure mode(s): {', '.join(missing)}")


def _check_doc_headers(root: Path) -> None:
    """A file at a derived-doc path that exists but lacks the generated-file header is not
    Blare's to overwrite (R19) -- caught here as well as by `init_inspection`'s narrower,
    no-state-file scenario."""
    header_bytes = GENERATED_DOC_HEADER.encode()
    for entry_filename in _ENTRY_FILENAMES.values():
        doc_path = _doc_path(root, entry_filename)
        if not doc_path.is_file():
            continue
        raw = _read_bytes(doc_path)
        first_line = raw.split(b"\n", 1)[0]
        if first_line != header_bytes:
            raise _err(
                doc_path,
                "lacks the generated-file header; this file is not Blare's to overwrite",
            )


def _load_state(file: Path) -> tuple[str, int]:
    raw = _read_bytes(file)
    try:
        doc = _YAML.load(raw)
    except Exception as exc:  # ruamel's parse failures aren't one exception type
        raise _err(file, f"is not valid YAML ({exc})") from exc
    if not isinstance(doc, dict):
        raise _err(file, "must be a YAML mapping with 'analyzed_sha' and 'schema_version'")
    sha = doc.get("analyzed_sha")
    version = doc.get("schema_version")
    missing = []
    if not isinstance(sha, str) or not sha:
        missing.append("analyzed_sha")
    # bool is an int subclass in Python; excluded explicitly so `true`/`false` don't parse
    # as a schema version.
    if not isinstance(version, int) or isinstance(version, bool):
        missing.append("schema_version")
    if missing:
        raise _err(file, f"is missing required field(s): {', '.join(missing)}")
    assert isinstance(sha, str)
    assert isinstance(version, int)
    return sha, version


def _check_schema_version(file: Path, version: int) -> None:
    if version != CURRENT_SCHEMA_VERSION:
        raise SchemaVersionError(
            cause=(
                f"{file} records schema version {version}, but this Blare understands "
                f"version {CURRENT_SCHEMA_VERSION}"
            ),
            next_action=(
                "Run the Blare version that matches the recorded schema version, or "
                "delete .blare/ and re-run full analysis (this discards any "
                "hand-recorded content)."
            ),
        )


# --- Config and stack resolution (R23) -------------------------------------------------


def _config_error(path: Path, problem: str) -> ConfigError:
    return ConfigError(
        cause=f"{path} {problem}",
        next_action=(
            f"Edit {path} to set 'stack' to one of the supported values: "
            f"{', '.join(supported_stacks())}."
        ),
    )


def _resolve_stack(
    root: Path, *, missing_is_error: bool
) -> tuple[ObservabilityStack, str, bool]:
    """Resolve `config.yaml`'s stack (R23). `missing_is_error` is true only for `load` in
    update mode -- every other caller (`empty_set`, and `load` in analyze mode, R16
    re-analysis included) defaults in memory and lets the write primitives create the file.

    Returns the resolved stack handle, its name, and whether the file existed (write-side
    concern: an existing config is preserved byte-identically and never rewritten).
    """
    path = root / _CONFIG_FILENAME
    if not path.is_file():
        if missing_is_error:
            raise _config_error(path, "does not exist")
        return get_stack(_DEFAULT_STACK_NAME), _DEFAULT_STACK_NAME, False
    # Deliberately not `_read_bytes`: config.yaml is outside R19's scope (spec, Artifacts
    # -- "validated by R23" instead), so an unreadable config must raise `ConfigError`
    # with R23's own next_action, not the generic StructuralValidationError every other
    # canonical file's read failure raises.
    try:
        raw = path.read_bytes()
    except OSError as exc:
        raise _config_error(path, f"could not be read ({exc.strerror or exc})") from exc
    try:
        doc = _YAML.load(raw)
    except Exception as exc:  # ruamel's parse failures aren't one exception type
        raise _config_error(path, f"is not valid YAML ({exc})") from exc
    if not isinstance(doc, dict):
        raise _config_error(path, "does not define a 'stack' value")
    stack_name = doc.get("stack")
    if not isinstance(stack_name, str) or not stack_name.strip():
        raise _config_error(path, "does not define a 'stack' value")
    # An unsupported name propagates get_stack's own UnsupportedStackError unchanged
    # rather than being wrapped here. stack.py's own docstring frames this as artifacts
    # "attaching the file name when propagating it", but there is nothing left to
    # attach: get_stack's next_action already hardcodes the literal ".blare/config.yaml"
    # (the location is fixed, never configurable -- spec, Artifacts), so the message
    # already names the file and, via its cause, the supported values. Left unwrapped on
    # purpose rather than reformatted to use this function's own computed `path` (which
    # could be an absolute Path, unlike the stable relative literal get_stack uses).
    stack = get_stack(stack_name)
    return stack, stack_name, True


# --- Public interface ------------------------------------------------------------------


def state_exists(root: Path) -> bool:
    """Whether `state.yaml` exists -- the R1-vs-R16-vs-R17 mode dispatch."""
    return (root / _STATE_FILENAME).is_file()


def init_inspection(root: Path) -> None:
    """R1's inverse refusal: called only when `state_exists(root)` is false. Refuses,
    naming every offending file, when any canonical entry-based file or derived-doc-path
    file already exists -- an existing `config.yaml` alone never triggers this."""
    offending: list[Path] = []
    for filename in _ENTRY_FILENAMES.values():
        path = root / filename
        if path.exists():
            offending.append(path)
    for filename in _ENTRY_FILENAMES.values():
        doc_path = _doc_path(root, filename)
        if doc_path.exists():
            offending.append(doc_path)
    if offending:
        names = ", ".join(str(p) for p in offending)
        raise PreexistingFilesError(
            cause=f"no state file exists, but these files already do: {names}",
            next_action=(
                "Remove or relocate these files before running blare analyze, or restore "
                "the missing .blare/state.yaml if this codebase was analyzed before."
            ),
        )


def empty_set(root: Path) -> ArtifactSet:
    """The fresh R1 baseline: every entry map empty, no recorded analysis yet. Resolves
    `config.yaml` if present (honoring an unsupported stack's refusal) and defaults to
    Prometheus in memory when absent -- never calls `load`."""
    stack, stack_name, config_existed = _resolve_stack(root, missing_is_error=False)
    return ArtifactSet(
        system_components={},
        failure_modes={},
        metrics={},
        metric_recommendations={},
        alert_recommendations={},
        coverage={},
        analyzed_sha=None,
        schema_version=CURRENT_SCHEMA_VERSION,
        stack_name=stack_name,
        stack=stack,
        config_existed=config_existed,
        raw_bytes={},
        documents={},
    )


def load(root: Path, mode: RunMode) -> ArtifactSet:
    """Load and structurally validate the canonical YAML (R19), resolve config/stack
    (R23), and check the schema version (R24). Raises `StateMissingError` if `state.yaml`
    is absent (the R17 identity) -- the fresh R1 path never reaches here; it starts from
    `empty_set` instead."""
    state_path = root / _STATE_FILENAME
    if not state_exists(root):
        raise StateMissingError(
            cause=f"{state_path} does not exist",
            next_action="Run `blare analyze` first to produce the artifact set.",
        )

    analyzed_sha, schema_version = _load_state(state_path)
    _check_schema_version(state_path, schema_version)

    files: dict[str, Path] = {}
    raw_bytes: dict[str, bytes] = {}
    documents: dict[str, CommentedSeq] = {}
    raw_items: dict[str, CommentedSeq] = {}
    for key, filename in _ENTRY_FILENAMES.items():
        path = root / filename
        files[key] = path
        if not path.is_file():
            raise _err(
                path,
                "does not exist, but state.yaml does (entry files must be present when "
                "state exists)",
            )
        raw, items = _load_entry_list(path)
        raw_bytes[filename] = raw
        documents[filename] = items
        raw_items[key] = items

    system_components = _load_entries(
        files["system_components"], raw_items["system_components"], "sm", _parse_system_component
    )
    failure_modes = _load_entries(
        files["failure_modes"], raw_items["failure_modes"], "fm", _parse_failure_mode
    )
    metrics = _load_entries(files["metrics"], raw_items["metrics"], "mx", _parse_metric)
    metric_recommendations = _load_entries(
        files["metric_recommendations"],
        raw_items["metric_recommendations"],
        "mr",
        _parse_metric_recommendation,
    )
    alert_recommendations = _load_entries(
        files["alert_recommendations"],
        raw_items["alert_recommendations"],
        "ar",
        _parse_alert_recommendation,
    )
    coverage = _load_coverage(files["coverage"], raw_items["coverage"])

    _check_dangling_references(
        system_components,
        failure_modes,
        metrics,
        metric_recommendations,
        alert_recommendations,
        coverage,
        files,
    )
    _check_acyclic(failure_modes, files["failure_modes"])
    _check_coverage_completeness(failure_modes, coverage, files["coverage"])
    _check_doc_headers(root)

    raw_bytes[_STATE_FILENAME] = _read_bytes(state_path)
    stack, stack_name, config_existed = _resolve_stack(
        root, missing_is_error=(mode is RunMode.UPDATE)
    )

    return ArtifactSet(
        system_components=system_components,
        failure_modes=failure_modes,
        metrics=metrics,
        metric_recommendations=metric_recommendations,
        alert_recommendations=alert_recommendations,
        coverage=coverage,
        analyzed_sha=analyzed_sha,
        schema_version=schema_version,
        stack_name=stack_name,
        stack=stack,
        config_existed=config_existed,
        raw_bytes=raw_bytes,
        documents=documents,
    )


def semantic_violations(s: ArtifactSet) -> list[Violation]:
    """R4-R5 in full, plus the excluded-empty-sets property (artifacts.md). Never raises
    for a violating set -- a violating set still loads; this seeds the R18 affected-phase
    queue and drives system-originated amendments. A misbehaving stack (one whose
    `validate_expression` raises rather than returning a verdict) is treated as an
    invalid-expression violation rather than allowed to crash the check."""
    violations: list[Violation] = []

    coverage_fms_by_alert: dict[str, set[str]] = {}
    for cov_entry in s.coverage.values():
        for arid in cov_entry.alert_ids:
            coverage_fms_by_alert.setdefault(arid, set()).add(cov_entry.failure_mode_id)

    for fm in s.failure_modes.values():
        entry = s.coverage.get(fm.id)
        # `load` guarantees a coverage entry for every failure mode; `entry` is only ever
        # None here for a hand-built ArtifactSet in a test that bypasses that guarantee,
        # in which case there is nothing to check for this failure mode.
        if entry is None:
            continue
        if fm.coverage_status == "excluded":
            metric_side_dirty = bool(
                entry.detecting_metric_ids or entry.metric_recommendation_ids
            ) or any(fm.id in mr.failure_mode_ids for mr in s.metric_recommendations.values())
            if metric_side_dirty:
                violations.append(
                    Violation(ViolationKind.EXCLUDED_WITH_METRIC_COVERAGE, (fm.id,))
                )
            alert_side_dirty = bool(entry.alert_ids) or any(
                fm.id in ar.failure_mode_ids for ar in s.alert_recommendations.values()
            )
            if alert_side_dirty:
                violations.append(
                    Violation(ViolationKind.EXCLUDED_WITH_ALERT_COVERAGE, (fm.id,))
                )
        elif not entry.alert_ids:
            violations.append(Violation(ViolationKind.UNMAPPED_FAILURE_MODE, (fm.id,)))

    for mr in s.metric_recommendations.values():
        if not mr.failure_mode_ids:
            violations.append(
                Violation(ViolationKind.EMPTY_LINKAGE_METRIC_RECOMMENDATION, (mr.id,))
            )

    for ar in s.alert_recommendations.values():
        if not ar.failure_mode_ids:
            violations.append(
                Violation(ViolationKind.EMPTY_LINKAGE_ALERT_RECOMMENDATION, (ar.id,))
            )

        try:
            verdict = s.stack.validate_expression(ar.expr)
        except Exception:
            # Defense-in-depth (artifacts.md's failure-mode test plan): a misbehaving
            # stack must not crash the run.
            violations.append(Violation(ViolationKind.INVALID_EXPRESSION, (ar.id,)))
        else:
            if not verdict.ok:
                violations.append(Violation(ViolationKind.INVALID_EXPRESSION, (ar.id,)))

        ranks = [
            _SEVERITY_RANK[s.failure_modes[fmid].severity]
            for fmid in ar.failure_mode_ids
            if fmid in s.failure_modes and s.failure_modes[fmid].severity in _SEVERITY_RANK
        ]
        if ranks:
            max_rank = max(ranks)
            if _SEVERITY_RANK.get(ar.severity, 0) < max_rank:
                violations.append(Violation(ViolationKind.ALERT_SEVERITY_BELOW_MAX, (ar.id,)))

        expected_fms = set(ar.failure_mode_ids)
        actual_fms = coverage_fms_by_alert.get(ar.id, set())
        if expected_fms != actual_fms:
            violations.append(Violation(ViolationKind.LINKAGE_INCONSISTENCY, (ar.id,)))

    return violations


def gap_counts(s: ArtifactSet) -> GapSummary:
    """Non-excluded failure modes split by coverage status (R13)."""
    alertable = metric_gap = excluded = 0
    for fm in s.failure_modes.values():
        if fm.coverage_status == "alertable":
            alertable += 1
        elif fm.coverage_status == "metric-gap":
            metric_gap += 1
        else:
            excluded += 1
    return GapSummary(alertable=alertable, metric_gap=metric_gap, excluded=excluded)


# --- batch_check: the per-batch content check (T1.5) ----------------------------------


def _check_regular_edit_schema(
    s: ArtifactSet,
    batch_phase: Phase,
    edit: Edit,
    live_ids: set[str],
) -> BatchVerdict | None:
    """The content half of the per-batch check for one non-coverage edit: phase
    consistency, payload schema (reusing the same parser `load` uses), and -- for alert
    edits -- expression syntax and rule-field validation via the set's stack. `live_ids`
    is the set of ids that exist *as of this point in the batch* -- it starts as a copy
    of every id already in `s` and is updated in place as ADD/REMOVE edits are processed
    (added on ADD, discarded on REMOVE), so a batch that adds an id and then updates or
    removes that same id later in the same batch is validated against the batch's actual
    running effect rather than a static pre-batch snapshot. Returns `None` when the edit
    passes, or the rejecting verdict."""
    spec = _TYPE_SPECS[edit.entry_type]
    assert spec.phase is not None and spec.prefix is not None  # not "coverage"
    if spec.phase is not batch_phase:
        return BatchVerdict(
            ok=False,
            message=(
                f"edit tagged for phase {batch_phase.value} targets "
                f"{edit.entry_type!r}, which belongs to phase {spec.phase.value}"
            ),
        )
    file = Path(spec.filename)

    if edit.op is EditOp.REMOVE:
        id_ = edit.payload_or_id
        if not isinstance(id_, str) or not id_:
            return BatchVerdict(ok=False, message="remove op requires a non-empty string id")
        # `live_ids` is a flattened union across every non-coverage entry type (ids are
        # globally unique, artifacts.md), so membership alone doesn't catch a remove
        # tagged with the wrong entry_type but naming a real id from a *different* type
        # -- e.g. removing a metric id through a "system_components" edit. Reject that
        # explicitly rather than letting it through to silently no-op in apply() (a
        # dict.pop on the wrong map never raises, so it would report success without
        # doing anything).
        if not id_.startswith(f"{spec.prefix}-"):
            return BatchVerdict(
                ok=False,
                message=(
                    f"remove targets {id_!r}, which does not use the {spec.prefix!r}- "
                    f"prefix required for {edit.entry_type!r}"
                ),
            )
        if id_ not in live_ids:
            return BatchVerdict(ok=False, message=f"remove targets unknown id {id_!r}")
        live_ids.discard(id_)
        return None

    payload = edit.payload_or_id
    if not isinstance(payload, dict):
        return BatchVerdict(
            ok=False,
            message=f"{edit.op.value} op on {edit.entry_type!r} requires a mapping payload",
        )
    try:
        id_ = _extract_prefixed_id(file, payload, spec.prefix)
    except StructuralValidationError as exc:
        return BatchVerdict(ok=False, message=exc.cause)

    if edit.op is EditOp.ADD and id_ in live_ids:
        return BatchVerdict(ok=False, message=f"duplicate id {id_!r}")
    if edit.op is EditOp.UPDATE and id_ not in live_ids:
        return BatchVerdict(ok=False, message=f"update targets unknown id {id_!r}")

    try:
        entry = spec.parser(file, id_, payload)
    except StructuralValidationError as exc:
        return BatchVerdict(ok=False, message=exc.cause)

    if edit.entry_type == "alert_recommendations":
        assert isinstance(entry, AlertRecommendation)
        rule_input = AlertRuleInput(
            name=entry.name,
            expr=entry.expr,
            for_duration=entry.for_duration,
            severity=entry.severity,
            annotations=dict(entry.annotations),
        )
        try:
            expr_verdict = s.stack.validate_expression(entry.expr)
        except Exception as exc:  # defense-in-depth: a misbehaving stack must not crash
            return BatchVerdict(ok=False, message=f"stack raised validating expression: {exc}")
        if not expr_verdict.ok:
            return BatchVerdict(ok=False, message=expr_verdict.message or "invalid expression")
        try:
            fields_verdict = s.stack.validate_rule_fields(rule_input)
        except Exception as exc:  # same defense, for the rule-fields validator
            return BatchVerdict(ok=False, message=f"stack raised validating rule fields: {exc}")
        if not fields_verdict.ok:
            return BatchVerdict(ok=False, message=fields_verdict.message or "invalid rule fields")

    if edit.op is EditOp.ADD:
        live_ids.add(id_)
    return None


_METRIC_SIDE_KEYS = frozenset({"detecting_metric_ids", "metric_recommendation_ids"})
_ALERT_SIDE_KEYS = frozenset({"alert_ids"})


def _check_coverage_edit_schema(
    s: ArtifactSet, batch_phase: Phase, edit: Edit
) -> BatchVerdict | None:
    """The content half of the per-batch check for one coverage edit: only `update` is
    ever legal (coverage keys are mechanical, artifacts.md), the batch must be tagged
    phase 3 or 4, and the payload may only carry that phase's owned side."""
    if edit.op is not EditOp.UPDATE:
        return BatchVerdict(
            ok=False,
            message=(
                "coverage entries accept only update ops -- their keys are mechanical "
                f"(op was {edit.op.value})"
            ),
        )
    if batch_phase not in (Phase.METRIC_COVERAGE, Phase.ALERT_RECOMMENDATIONS):
        return BatchVerdict(
            ok=False,
            message=(
                f"coverage edits must be tagged phase 3 or phase 4, got phase {batch_phase.value}"
            ),
        )
    payload = edit.payload_or_id
    if not isinstance(payload, dict):
        return BatchVerdict(ok=False, message="coverage update requires a mapping payload")
    fm_id = payload.get("failure_mode_id")
    if not isinstance(fm_id, str) or not fm_id:
        return BatchVerdict(
            ok=False, message="coverage update requires a non-empty string 'failure_mode_id'"
        )
    if fm_id not in s.failure_modes:
        return BatchVerdict(
            ok=False, message=f"coverage update targets unknown failure_mode_id {fm_id!r}"
        )

    owned_keys = _METRIC_SIDE_KEYS if batch_phase is Phase.METRIC_COVERAGE else _ALERT_SIDE_KEYS
    other_keys = _ALERT_SIDE_KEYS if batch_phase is Phase.METRIC_COVERAGE else _METRIC_SIDE_KEYS
    present_other = other_keys & payload.keys()
    if present_other:
        return BatchVerdict(
            ok=False,
            message=(
                f"phase {batch_phase.value} coverage edit for {fm_id!r} touches the "
                f"other side's field(s): {', '.join(sorted(present_other))}"
            ),
        )
    for key in owned_keys & payload.keys():
        value = payload[key]
        if not isinstance(value, list) or not all(isinstance(v, str) for v in value):
            return BatchVerdict(ok=False, message=f"{key!r} must be a list of strings")
    return None


def batch_check(s: ArtifactSet, b: EditBatch) -> BatchVerdict:
    """The per-batch content check (architecture, Edit-proposal protocol): payload
    schema, phase consistency (the tagged phase's owned side for coverage entries), and
    R19's structural rules -- uniqueness, reference integrity including removals,
    acyclicity -- applied to the resulting candidate, so an accepted batch always passes
    its own next load. Never raises for a content problem (`BatchVerdict.ok=False`
    carries the reason instead); only a programmer error (an unrecognized `entry_type`
    reaching `apply` after passing every check above, which cannot happen through this
    function's own dispatch) would propagate."""
    # The ids that exist as of "now" while walking the batch in order -- starts as every
    # id already in `s` and is updated in place by `_check_regular_edit_schema` as
    # ADD/REMOVE edits are processed, so an ADD followed later in the same batch by an
    # UPDATE or REMOVE of that same id validates against the batch's running effect
    # rather than a static pre-batch snapshot (a batch is never required to touch each
    # id only once).
    live_ids = (
        set(s.system_components)
        | set(s.failure_modes)
        | set(s.metrics)
        | set(s.metric_recommendations)
        | set(s.alert_recommendations)
    )

    for edit in b.edits:
        if edit.entry_type not in _TYPE_SPECS:
            return BatchVerdict(ok=False, message=f"unknown entry_type {edit.entry_type!r}")
        if edit.entry_type == "coverage":
            verdict = _check_coverage_edit_schema(s, b.phase, edit)
        else:
            verdict = _check_regular_edit_schema(s, b.phase, edit, live_ids)
        if verdict is not None:
            return verdict

    candidate = apply(s, b)

    files = {key: Path(spec.filename) for key, spec in _TYPE_SPECS.items()}
    try:
        _check_dangling_references(
            candidate.system_components,
            candidate.failure_modes,
            candidate.metrics,
            candidate.metric_recommendations,
            candidate.alert_recommendations,
            candidate.coverage,
            files,
        )
        _check_acyclic(candidate.failure_modes, files["failure_modes"])
        _check_coverage_completeness(candidate.failure_modes, candidate.coverage, files["coverage"])
    except StructuralValidationError as exc:
        return BatchVerdict(ok=False, message=exc.cause)

    return BatchVerdict(ok=True)


# --- apply: the pure candidate, with mechanical coverage completeness (T1.5) ----------


def _apply_add_update_or_remove[EntryT](
    edit: Edit,
    target: dict[str, EntryT],
    file: Path,
    prefix: str,
    parser: Callable[[Path, str, Mapping[str, object]], EntryT],
) -> str:
    """Mutate `target` (a copy `apply` owns, never the caller's) in place per `edit`'s
    op; returns the affected id -- `apply`'s failure-mode bookkeeping uses it to drive
    mechanical coverage completeness, every other entry type ignores it. Assumes `edit`
    already passed `batch_check`'s content validation; a malformed edit reaching here
    (bypassing `batch_check`) is a programmer error and raises."""
    if edit.op is EditOp.REMOVE:
        id_ = edit.payload_or_id
        assert isinstance(id_, str), "remove op must carry a string id"
        target.pop(id_, None)
        return id_
    payload = edit.payload_or_id
    assert isinstance(payload, dict), f"{edit.op.value} op must carry a mapping payload"
    id_ = _extract_prefixed_id(file, payload, prefix)
    target[id_] = parser(file, id_, payload)
    return id_


def _coerce_str_tuple(value: object) -> tuple[str, ...]:
    if isinstance(value, tuple):
        return cast(tuple[str, ...], value)
    assert isinstance(value, list), "coverage side field must be a list of strings"
    return tuple(value)


def _apply_coverage_edit(edit: Edit, phase: Phase, coverage: dict[str, CoverageEntry]) -> None:
    """Merge one coverage edit's owned side into `coverage` in place, leaving the other
    side untouched (architecture: "apply merges the owned side and leaves the other
    untouched")."""
    payload = edit.payload_or_id
    assert isinstance(payload, dict), "coverage update must carry a mapping payload"
    fm_id = payload["failure_mode_id"]
    assert isinstance(fm_id, str)
    existing = coverage.get(fm_id, CoverageEntry(fm_id, (), (), ()))
    if phase is Phase.METRIC_COVERAGE:
        coverage[fm_id] = CoverageEntry(
            failure_mode_id=fm_id,
            detecting_metric_ids=_coerce_str_tuple(
                payload.get("detecting_metric_ids", existing.detecting_metric_ids)
            ),
            metric_recommendation_ids=_coerce_str_tuple(
                payload.get("metric_recommendation_ids", existing.metric_recommendation_ids)
            ),
            alert_ids=existing.alert_ids,
        )
    else:
        coverage[fm_id] = CoverageEntry(
            failure_mode_id=fm_id,
            detecting_metric_ids=existing.detecting_metric_ids,
            metric_recommendation_ids=existing.metric_recommendation_ids,
            alert_ids=_coerce_str_tuple(payload.get("alert_ids", existing.alert_ids)),
        )


def apply(s: ArtifactSet, b: EditBatch) -> ArtifactSet:
    """Apply `b` to `s`, returning a new `ArtifactSet` -- pure, `s` is never mutated
    (architecture: "a later apply must return a new ArtifactSet rather than mutate this
    one in place"). Coverage completeness is mechanical, never the agent's: adding a
    failure mode creates its empty coverage entry in the candidate, removing one deletes
    it -- so no reachable candidate can violate the one-entry-per-failure-mode rule
    (artifacts.md)."""
    system_components = dict(s.system_components)
    failure_modes = dict(s.failure_modes)
    metrics = dict(s.metrics)
    metric_recommendations = dict(s.metric_recommendations)
    alert_recommendations = dict(s.alert_recommendations)
    coverage = dict(s.coverage)

    added_failure_modes: set[str] = set()
    removed_failure_modes: set[str] = set()

    for edit in b.edits:
        if edit.entry_type == "system_components":
            _apply_add_update_or_remove(
                edit, system_components, Path("system-map.yaml"), "sm", _parse_system_component
            )
        elif edit.entry_type == "failure_modes":
            fm_id = _apply_add_update_or_remove(
                edit, failure_modes, Path("failure-modes.yaml"), "fm", _parse_failure_mode
            )
            if edit.op is EditOp.ADD:
                added_failure_modes.add(fm_id)
                removed_failure_modes.discard(fm_id)
            elif edit.op is EditOp.REMOVE:
                removed_failure_modes.add(fm_id)
                added_failure_modes.discard(fm_id)
        elif edit.entry_type == "metrics":
            _apply_add_update_or_remove(edit, metrics, Path("metrics.yaml"), "mx", _parse_metric)
        elif edit.entry_type == "metric_recommendations":
            _apply_add_update_or_remove(
                edit,
                metric_recommendations,
                Path("metric-recommendations.yaml"),
                "mr",
                _parse_metric_recommendation,
            )
        elif edit.entry_type == "alert_recommendations":
            _apply_add_update_or_remove(
                edit,
                alert_recommendations,
                Path("alert-recommendations.yaml"),
                "ar",
                _parse_alert_recommendation,
            )
        elif edit.entry_type == "coverage":
            continue  # handled in the second pass below, after mechanical completeness
        else:
            raise ValueError(f"unknown entry_type {edit.entry_type!r}")

    for fm_id in added_failure_modes:
        coverage.setdefault(fm_id, CoverageEntry(fm_id, (), (), ()))
    for fm_id in removed_failure_modes:
        coverage.pop(fm_id, None)

    for edit in b.edits:
        if edit.entry_type == "coverage":
            _apply_coverage_edit(edit, b.phase, coverage)

    return ArtifactSet(
        system_components=system_components,
        failure_modes=failure_modes,
        metrics=metrics,
        metric_recommendations=metric_recommendations,
        alert_recommendations=alert_recommendations,
        coverage=coverage,
        analyzed_sha=s.analyzed_sha,
        schema_version=s.schema_version,
        stack_name=s.stack_name,
        stack=s.stack,
        config_existed=s.config_existed,
        raw_bytes=s.raw_bytes,
        documents=s.documents,
    )


# --- referencing_phases: the reference half of the amendment blast radius (T1.5) ------


def referencing_phases(s: ArtifactSet, changed_ids: set[str]) -> set[Phase]:
    """The phases owning entries that reference any id in `changed_ids` -- coverage
    entries attributed by side (metric side references -> phase 3, alert side -> phase
    4, artifacts.md). One hop only: the orchestrator's amendment recompute is what loops
    this to a fixpoint over a growing changed-id set, not this function."""
    phases: set[Phase] = set()
    for component in s.system_components.values():
        if any(dep in changed_ids for dep in component.depends_on):
            phases.add(Phase.SYSTEM_MAP)
    for fm in s.failure_modes.values():
        if any(cause in changed_ids for cause in fm.caused_by):
            phases.add(Phase.FAILURE_MODES)
    for mr in s.metric_recommendations.values():
        if (mr.metric_id is not None and mr.metric_id in changed_ids) or any(
            fmid in changed_ids for fmid in mr.failure_mode_ids
        ):
            phases.add(Phase.METRIC_COVERAGE)
    for ar in s.alert_recommendations.values():
        if any(fmid in changed_ids for fmid in ar.failure_mode_ids):
            phases.add(Phase.ALERT_RECOMMENDATIONS)
    for cov in s.coverage.values():
        if any(mid in changed_ids for mid in cov.detecting_metric_ids) or any(
            mrid in changed_ids for mrid in cov.metric_recommendation_ids
        ):
            phases.add(Phase.METRIC_COVERAGE)
        if any(arid in changed_ids for arid in cov.alert_ids):
            phases.add(Phase.ALERT_RECOMMENDATIONS)
    return phases


# --- render_docs: deterministic derived-doc rendering (T1.5) -------------------------


def _doc_header_and_title(title: str) -> str:
    return f"{GENERATED_DOC_HEADER}\n\n# {title}\n\n"


def _render_system_map(s: ArtifactSet) -> bytes:
    parts = [_doc_header_and_title("System map")]
    for c in sorted(s.system_components.values(), key=lambda c: c.id):
        parts.append(f"## {c.id}: {c.name}\n\n")
        parts.append(f"- kind: {c.kind}\n")
        parts.append(f"- description: {c.description}\n")
        parts.append(f"- depends_on: {', '.join(c.depends_on) or '(none)'}\n\n")
    return "".join(parts).encode()


def _render_failure_modes(s: ArtifactSet) -> bytes:
    parts = [_doc_header_and_title("Failure modes")]
    for fm in sorted(s.failure_modes.values(), key=lambda fm: fm.id):
        parts.append(f"## {fm.id}: {fm.title}\n\n")
        parts.append(f"- description: {fm.description}\n")
        parts.append(f"- severity: {fm.severity}\n")
        parts.append(f"- user_visible: {fm.user_visible}\n")
        parts.append(f"- coverage_status: {fm.coverage_status}\n")
        parts.append(f"- caused_by: {', '.join(fm.caused_by) or '(none)'}\n")
        if fm.exclusion_reason is not None:
            parts.append(f"- exclusion_reason: {fm.exclusion_reason}\n")
        parts.append("\n")
    return "".join(parts).encode()


def _render_metrics(s: ArtifactSet) -> bytes:
    parts = [_doc_header_and_title("Implemented metrics")]
    for m in sorted(s.metrics.values(), key=lambda m: m.id):
        parts.append(f"## {m.id}: {m.name}\n\n")
        parts.append(f"- type: {m.type}\n")
        parts.append(f"- labels: {', '.join(m.labels) or '(none)'}\n")
        parts.append(f"- emitted_at: {', '.join(m.emitted_at) or '(none)'}\n")
        parts.append(f"- description: {m.description}\n\n")
    return "".join(parts).encode()


def _render_metric_recommendations(s: ArtifactSet) -> bytes:
    parts = [_doc_header_and_title("Metric recommendations")]
    for mr in sorted(s.metric_recommendations.values(), key=lambda mr: mr.id):
        parts.append(f"## {mr.id}\n\n")
        parts.append(f"- kind: {mr.kind}\n")
        if mr.metric_id is not None:
            parts.append(f"- metric_id: {mr.metric_id}\n")
        parts.append(f"- failure_mode_ids: {', '.join(mr.failure_mode_ids) or '(none)'}\n")
        parts.append(f"- rationale: {mr.rationale}\n")
        parts.append(f"- details: {mr.details}\n\n")
    return "".join(parts).encode()


def _render_alert_recommendations(s: ArtifactSet) -> bytes:
    parts = [_doc_header_and_title("Alert recommendations")]
    for ar in sorted(s.alert_recommendations.values(), key=lambda ar: ar.id):
        parts.append(f"## {ar.id}: {ar.name}\n\n")
        parts.append(f"- severity: {ar.severity}\n")
        parts.append(f"- failure_mode_ids: {', '.join(ar.failure_mode_ids) or '(none)'}\n\n")
        rule_input = AlertRuleInput(
            name=ar.name,
            expr=ar.expr,
            for_duration=ar.for_duration,
            severity=ar.severity,
            annotations=dict(ar.annotations),
        )
        shape = s.stack.alert_rule_shape(rule_input)
        buf = io.StringIO()
        _YAML.dump(shape, buf)
        parts.append("```yaml\n")
        parts.append(buf.getvalue())
        parts.append("```\n\n")
    return "".join(parts).encode()


def _render_coverage(s: ArtifactSet) -> bytes:
    gaps = gap_counts(s)
    parts = [_doc_header_and_title("Coverage mapping")]
    parts.append("## Gap report\n\n")
    parts.append(f"- alertable: {gaps.alertable}\n")
    parts.append(f"- metric-gap: {gaps.metric_gap}\n")
    parts.append(f"- excluded: {gaps.excluded}\n\n")
    parts.append("## Entries\n\n")
    for cov in sorted(s.coverage.values(), key=lambda cov: cov.failure_mode_id):
        parts.append(f"### {cov.failure_mode_id}\n\n")
        parts.append(
            f"- detecting_metric_ids: {', '.join(cov.detecting_metric_ids) or '(none)'}\n"
        )
        parts.append(
            "- metric_recommendation_ids: "
            f"{', '.join(cov.metric_recommendation_ids) or '(none)'}\n"
        )
        parts.append(f"- alert_ids: {', '.join(cov.alert_ids) or '(none)'}\n\n")
    return "".join(parts).encode()


def render_docs(s: ArtifactSet) -> dict[Path, bytes]:
    """Render every derived doc from `s`'s current entries: the generated-file header
    first, entries sorted by id, `coverage.md` carrying the gap report. Deterministic --
    unchanged YAML renders byte-identically (R9) -- since it is a pure function of `s`'s
    entries. Keys are relative to `.blare/` (`docs/<name>.md`); `write_docs` joins them
    with `root`."""
    return {
        Path(_DOCS_DIRNAME) / "system-map.md": _render_system_map(s),
        Path(_DOCS_DIRNAME) / "failure-modes.md": _render_failure_modes(s),
        Path(_DOCS_DIRNAME) / "metrics.md": _render_metrics(s),
        Path(_DOCS_DIRNAME) / "metric-recommendations.md": _render_metric_recommendations(s),
        Path(_DOCS_DIRNAME) / "alert-recommendations.md": _render_alert_recommendations(s),
        Path(_DOCS_DIRNAME) / "coverage.md": _render_coverage(s),
    }


# --- raw_bytes_match: the R20 write-time re-check (T1.5) -----------------------------


def raw_bytes_match(root: Path, s: ArtifactSet) -> bool:
    """Whether the canonical YAML set (entry-based files plus state -- `config.yaml`
    excluded) on disk still matches what `s` loaded, byte for byte. A pure comparison,
    no validation: a mid-run hand edit surfaces as R20's "changed mid-run" abort, not a
    validation error. The fresh-run baseline (`s.raw_bytes == {}`) means any
    compared-path file appearing mid-run fails the check."""
    for filename in _CANONICAL_YAML_FILENAMES:
        path = root / filename
        recorded = s.raw_bytes.get(filename)
        if recorded is None:
            if path.exists():
                return False
            continue
        try:
            current = path.read_bytes()
        except OSError:
            return False
        if current != recorded:
            return False
    return True


# --- Write primitives (T1.5): surgical entries+config, docs, state -------------------


def _write_file(path: Path, data: bytes) -> None:
    """The write seam every primitive below goes through -- what the failure-mode test
    plan's "`_write_file` monkeypatched" targets. Wraps a filesystem failure as
    `WriteError` naming the file (R20's crash case; artifacts.md, Failure visibility)."""
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    except OSError as exc:
        raise WriteError(
            cause=f"{path} could not be written ({exc.strerror or exc})",
            next_action=(
                "Nothing under .blare/ is committed until you commit it yourself: check "
                "git status and restore or clean up the partial write, then re-run blare."
            ),
        ) from exc


def _dump_yaml_bytes(data: object) -> bytes:
    buf = io.BytesIO()
    _YAML.dump(data, buf)
    return buf.getvalue()


def _to_commented_map(fields: Mapping[str, object]) -> CommentedMap:
    cm = CommentedMap()
    for key, value in fields.items():
        cm[key] = value
    return cm


def _merge_entry_file(
    spec: _TypeSpec, loaded_seq: CommentedSeq, current_map: Mapping[str, object]
) -> tuple[CommentedSeq, bool]:
    """Surgically merge `current_map` (the final in-memory entries) against `loaded_seq`
    (the round-trip YAML `load` parsed), returning a new sequence: an entry whose parsed
    value is unchanged keeps its exact original object -- hand-formatting, comments,
    quote style included (architecture, Determinism) -- a changed entry's item is
    replaced, a removed one is dropped, and new entries are appended in id order.
    `loaded_seq` (an `ArtifactSet.documents` entry, potentially shared with other
    candidates derived from the same loaded set via `apply`) is deep-copied first and
    never itself mutated, keeping this a pure function despite `CommentedSeq` being a
    mutable container. Returns the merged sequence and whether anything actually
    changed."""
    merged: CommentedSeq = copy.deepcopy(loaded_seq)
    changed = False
    seen_ids: set[str] = set()
    kept_indices: list[int] = []
    for index, item in enumerate(merged):
        item_id = item.get(spec.id_key)
        assert isinstance(item_id, str)  # already validated at load time
        seen_ids.add(item_id)
        if item_id not in current_map:
            changed = True
            continue
        original_entry = spec.parser(Path(spec.filename), item_id, item)
        if original_entry != current_map[item_id]:
            changed = True
            merged[index] = _to_commented_map(spec.serializer(current_map[item_id]))
        kept_indices.append(index)

    for index in sorted(set(range(len(merged))) - set(kept_indices), reverse=True):
        del merged[index]

    new_ids = sorted(set(current_map) - seen_ids)
    if new_ids:
        changed = True
    for new_id in new_ids:
        merged.append(_to_commented_map(spec.serializer(current_map[new_id])))

    return merged, changed


def write_entries_and_config(root: Path, s: ArtifactSet) -> WriteReport:
    """Write the six entry-based files plus `config.yaml`, surgically: a file with no
    changed entries is not rewritten, except that a fresh run (`s.documents == {}`)
    creates every canonical file, zero-entry files included, so the written set
    satisfies load's "entry files present when state exists" rule. `config.yaml` is
    created only when it did not already exist (R23); an existing one is preserved
    byte-identically (never rewritten). Raises `WriteError` naming the failing file if a
    write fails partway; files already written land on disk regardless."""
    written: list[Path] = []
    skipped: list[Path] = []

    for key, filename in _ENTRY_FILENAMES.items():
        path = root / filename
        spec = _TYPE_SPECS[key]
        current_map = getattr(s, key)
        if filename in s.documents:
            merged_seq, changed = _merge_entry_file(spec, s.documents[filename], current_map)
            if not changed:
                skipped.append(path)
                continue
        else:
            merged_seq = CommentedSeq()
            for entry_id in sorted(current_map):
                merged_seq.append(_to_commented_map(spec.serializer(current_map[entry_id])))
        _write_file(path, _dump_yaml_bytes(merged_seq))
        written.append(path)

    config_path = root / _CONFIG_FILENAME
    if s.config_existed:
        skipped.append(config_path)
    else:
        _write_file(config_path, _dump_yaml_bytes({"stack": s.stack_name}))
        written.append(config_path)

    return WriteReport(written=tuple(written), skipped=tuple(skipped))


def write_docs(root: Path, s: ArtifactSet) -> WriteReport:
    """Restore every derived doc to the canonical form of `s`'s current entries (R10):
    unconditional, since restoration -- not skip-if-unchanged -- is what R10 promises;
    when nothing changed, the restored bytes equal what was already there, so R9's zero
    diff still holds at the git level even though every file is rewritten."""
    written: list[Path] = []
    for rel_path, content in render_docs(s).items():
        path = root / rel_path
        _write_file(path, content)
        written.append(path)
    return WriteReport(written=tuple(written), skipped=())


def write_state(root: Path, s: ArtifactSet, analyzed_sha: str) -> WriteReport:
    """Write `state.yaml` last (R20). `analyzed_sha` enters only here, never through
    batches. When `s` was loaded from an existing state file and `analyzed_sha` equals
    what was already recorded, the file is left untouched -- byte for byte -- rather
    than reformatted, since R9 permits exactly two changes in a no-op run and "the
    analyzed SHA advancing" is not one of them when it does not advance."""
    path = root / _STATE_FILENAME
    if _STATE_FILENAME in s.raw_bytes and analyzed_sha == s.analyzed_sha:
        return WriteReport(written=(), skipped=(path,))
    data = {"analyzed_sha": analyzed_sha, "schema_version": s.schema_version}
    _write_file(path, _dump_yaml_bytes(data))
    return WriteReport(written=(path,), skipped=())


__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "GENERATED_DOC_HEADER",
    "StructuralValidationError",
    "StateMissingError",
    "PreexistingFilesError",
    "ConfigError",
    "SchemaVersionError",
    "WriteError",
    "SystemComponent",
    "FailureMode",
    "Metric",
    "MetricRecommendation",
    "AlertRecommendation",
    "CoverageEntry",
    "GapSummary",
    "ArtifactSet",
    "WriteReport",
    "state_exists",
    "init_inspection",
    "empty_set",
    "load",
    "semantic_violations",
    "gap_counts",
    "batch_check",
    "apply",
    "referencing_phases",
    "render_docs",
    "raw_bytes_match",
    "write_entries_and_config",
    "write_docs",
    "write_state",
]
